# Acknowledgments {.unnumbered}

```{r}
#| label: setup
#| echo: false
#| output: false

# library(here)

source(here::here("R/quarto-setup.R"))
```

I would like to acknowledge the following persons and organizations:

To Salete Perroni (Sal), my partner in life and in the fight.

To my Mother, for her unconditional love.

To my sister and my brother, for their love and partnership in life.

To my friends in science, [Alicia Rafaelly Vilefort Sales](https://orcid.org/0000-0003-0004-4487), [Juliana Viana Mendes](https://orcid.org/0000-0002-8222-5240), and [Maria Augusta Medeiros de Andrade](https://orcid.org/0000-0002-9283-9967).

To my friend and Professor [Humberto Miguel Garay Malpartida](https://orcid.org/0000-0002-1164-2055), for his support; for his principles; and for his integrity, which was demonstrated when the need arose.

To Professor [Camilo Rodrigues Neto](https://orcid.org/0000-0001-6783-6695), for introducing me to and teaching me about the science of complex systems since 2012; for guiding my dissertation; for the patience and the virtue in taking on and mediating the process of transitioning my guidance in my master's degree after the breakdown of relations with my former supervisor.

To Professor [Carlos Molina Mendes](https://orcid.org/0000-0003-2916-4415), for the speed, impartiality, patience, and virtue in mediating the process of transitioning my guidance in my master's degree.

To my fellow friends: Alex Azevedo Martins; Amanda Moreira; Augusto Amado, Carina (Cacau) Prado; Cauê Teles; Ítalo Alves Bezerra do Nascimento; Júlia Mafra; Leonardo Kazuhiko Kawazoe; Letícia Nery de Figueiredo; and Reginaldo Noveli.

To [President Lula](https://lula.com.br/) (Yes!), who saved Brazil from fascism and approved the long-overdue adjustments to postgraduate scholarships.

To the local Student Movements, which truly support their category, __unlike__ the [National Association of Postgraduates (ANPG)](https://www.anpg.org.br/), the [Association of Postgraduates (APG) Helenira 'Preta' Rezende)](https://linktr.ee/apguspcapital) of the University of São Paulo (USP), and the [Central Directory of Students (DCE) Alexandre Vannucchi Leme](https://www.dceusp.org.br/) of USP.

To the [Support Program for Student Permanence and Education (PAPFE)](https://prip.usp.br/apoio-estudantil/) of USP, which enabled me to get this far.

To the [Coordination for the Improvement of Higher Education Personnel (CAPES)](https://www.gov.br/capes/), for funding this work and enabling my presence in postgraduate studies.
