<!-- %:::% .common h1 begin %:::% -->
# Conclusion {#sec-conclusion}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

According to Popper, the aim of science is to provide "satisfactory explanations of whatever strikes us as being in need of explanation" [@popper1979, p. 193]. This study, using what is arguably the largest dataset on chronotype collected within a single time zone—balanced to reflect population proportions at the time of data collection—found no support for the latitude hypothesis (Cohen's $f^2 = 0.012137120$). This result contributes meaningful evidence to the understanding of circadian rhythm regulation, offering a clear and satisfactory answer to the central research question of this thesis: "Is latitude associated with chronotype?" The answer is **No**.

These findings are consistent with those of @leocadio-miguel2017, who reported a similar effect size (Cohen's $f^2 = 0.004143174$). However, the earlier study did not apply a minimum effect size criterion, leading to a misleading conclusion.

Several factors could explain the lack of an association between latitude and chronotype ― or, as Jürgen Aschoff might have phrased it, the absence of "ecological significance" [@aschoff1972]. For instance, if latitude does affect the circadian system, the effect may be too small to detect or could be overshadowed by other influences, such as social habits, work schedules, or the use of artificial light [@bohlen1973; @skeldon2021]. Additionally, the difference in solar exposure across latitudes may be insufficient to produce a meaningful effect on the circadian system, which is highly sensitive to light. Even minor variations in light exposure can yield significant physiological responses, suggesting that latitude alone may not be a strong predictor of chronotype.

These results suggest that the relationship between latitude and the circadian system is far more complex than anticipated. In human contexts, the perception of such an effect may have arisen from statistical misinterpretations, driven by ritualistic reliance on Null Hypothesis Significance Testing (NHST) and confirmation bias, rather than a critical evaluation of the data.

## Limitations

While this study provides valuable insights, it is essential to acknowledge certain limitations that may influence the interpretation of the findings. First, the data collection occurred predominantly during a single week in spring, as summer approached, which limited the photoperiod variability between regions. A better approach would involve data collection across different seasons, particularly during winter, when photoperiod differences are more pronounced between equatorial and polar regions.

Additionally, the use of the Munich Chronotype Questionnaire (MCTQ), while a validated instrument, introduces the potential for recall and social desirability biases inherent to self-reported measures. However, the large sample size likely mitigates these biases, as predicted by the law of large numbers [@degroot2012, p. 352]. Furthermore, at the time of data collection, the MCTQ had not yet been officially validated in Portuguese (this was only introduced in 2020 by @reis2020a), which may have introduced minor inconsistencies, though its nature as a sleep log suggests this impact was minimal.

Another factor to consider is the timing of data collection relative to the start of Daylight Saving Time (DST) in Brazil. On the day data collection commenced (October 15th, 2017 – `{r} analysis_data_per_nrow_2017_10_15 |> format_to_md_latex()` $80.153\%$ of the data used in this analysis were collected on this day), a significant portion of respondents adjusted their clocks forward by one hour. While this could theoretically influence their responses, the questions were specifically designed to capture daily routines, which were not affected by the DST adjustment at that moment. Furthermore, any potential effect of DST would likely strengthen the latitude hypothesis; however, this was not supported by the data.

These limitations, while noteworthy, do not undermine the study's findings but rather highlight areas for refinement in future research.

## Directions for Future Research

This thesis proposed using a global modeling approach to investigate the latitude-chronotype relationship. However, as demonstrated by the results of this study and others, no significant effect of latitude on chronotype was identified. That said, it remains possible that if such a phenomenon exists, it could be captured through a localized approach, such as agent-based modeling. This approach would simulate an environment where agents are exposed to varying light levels, while accounting for their endogenous rhythms and the circadian clock's phase-response curve to light. The data from this thesis could serve to calibrate and validate this model.

<!-- textual end -->

```{=latex}
\postextual

\begingroup
\renewcommand{\baselinestretch}{1}
\setcounter{footnote}{0}
\renewcommand{\thefootnote}{\fnsymbol{footnote}}
\printbibliography[heading=bibheading]
\endgroup

\tocskipone
\tocprintchapternonum
\addcontentsline{toc}{chapter}{\newbibname}
```
