<!-- %:::% index begin %:::% -->
# Introduction {#sec-introduction}

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

<!-- %:::% index pdf begin %:::% -->
There has been a long-standing debate in the chronobiology community regarding the relationship between latitude and circadian phenotypes (chronotypes) [@bohlen1973; @pittendrigh1991; @leocadio-miguel2017; @zerbini2021; @skeldon2021], with many assuming that this association is well-established. The hypothesis is based on the varying amounts of solar radiation experienced by populations across different latitudes. Since light exposure serves as a primary zeitgeber — a periodic environmental cue that influences or regulates biological rhythms [@pittendrigh1960] — such variations, along with temperature differences, are thought to result in observable differences in chronotype distributions globally. This thesis investigates the so-called latitude or environmental hypothesis in human circadian phenotypes, addressing the question: *Is latitude associated with chronotype?*

The central hypothesis is that *latitude is associated with human chronotype distributions*, with populations closer to the equator exhibiting, on average, a shorter or more morning-oriented circadian phenotype compared to those living near the poles [@bohlen1973; @pittendrigh1991; @roenneberg2003; @randler2008; @hut2013; @leocadio-miguel2017; @randler2017]. The primary objective of this study is to model and test this hypothesis by critically examining whether a significant association exists between latitude and circadian phenotypes in the Brazilian population.

This study emerged from an insightful debate with my former supervisor, sparked by results published in 2017 in *Nature Scientific Reports* [@leocadio-miguel2017]. In this paper, the authors conclude, as the theory suggests, that there is a significant association between latitude and chronotype in the Brazilian population. However, the results were not as clear-cut as suggested, and the methodology used to test the hypothesis was not optimal. This thesis revisits the hypothesis using an improved statistical approach, aiming to provide a more accurate and reliable answer to the research question.

In the following chapters, the latitude hypothesis is explored using Popper's hypothetical-deductive method [@popper1979] and an enhanced approach to Null Hypothesis Significance Testing (NHST), rooted in the original Neyman-Pearson framework for data testing [@neyman1928; @neyman1928a; @perezgonzalez2015]. This exploration involves a series of analyses conducted on a large dataset comprising `{r} results_vars$ea_analysis_sample_n |> format_to_md_latex()` individuals, collected from the Brazilian population in 2017. The dataset is based on the Munich Chronotype Questionnaire (MCTQ) [@roenneberg2003; @roenneberg2012a], and includes data on sleep habits and demographic characteristics from all of Brazil's states.

It is important to emphasize that this thesis does not aim to propose or discuss the mechanisms underlying the latitude-chronotype relationship. Instead, it focuses solely on the statistical association between them. If a cause-effect relationship exists, it must be preceded by, at the very least, an association — something this thesis aims to uncover.

The analyses utilize nested multiple regression models to evaluate the additional variance explained and the effect size when latitude is included as a predictor of chronotype. The results are then compared with those obtained from a restricted model that does not have latitude as a predictor. This method of procedure builds on the method used in @leocadio-miguel2017. The results will contribute to the ongoing debate on the latitude-chronotype relationship, offering new evidences into how environmental factors influence human circadian rhythms.

In accordance with the [graduate program regulation](https://leginf.usp.br/?resolucao=resolucao-copgr-no-7829-de-03-de-outubro-de-2019#:~:text=XI%20%E2%80%93%20PROCEDIMENTOS%20PARA%20DEP%C3%93SITO%20DA%20DISSERTA%C3%87%C3%83O), this thesis follows an [article-based format](https://en.wikipedia.org/wiki/Collection_of_articles), inspired by the structure of @reis2020's PhD thesis. Chapters [-@sec-on-chronobiology] and [-@sec-on-the-latitude-hypothesis] consist of a series of essays and literature reviews related to the thesis topic, while Chapter [-@sec-latitude-hypothesis-article] presents the core investigation, including an article detailing the hypothesis test and addressing the central research question. Finally, Chapter [@sec-conclusion] offers conclusions, discusses limitations, and proposes directions for future research. Additionally, supplementary materials are provided to offer a richer, more comprehensive understanding of the research, and the reader is encouraged to explore them in detail.

::: {.content-visible when-format="html"}
All analyses in this thesis are fully reproducible and were conducted using the [R programming language](https://www.r-project.org/) [@rcoreteam] alongside the [Quarto](https://quarto.org/) publishing system [@allaire].
:::

::: {.content-visible when-format="pdf"}
All analyses in this thesis are fully reproducible and were conducted using the [R programming language](https://www.r-project.org/) [@rcoreteam] alongside the [Quarto](https://quarto.org/) publishing system [@allaire]. Given the thesis's data-centric nature, it is best experienced online. To view the digital version
visit <https://danielvartan.github.io/mastersthesis>.

The thesis code repository is available on GitHub at <https://github.com/danielvartan/mastersthesis>, and the research compendium can be accessed via [The Open Science Framework](https://osf.io/) at the following link:  <https://doi.org/10.17605/OSF.IO/YGKTS>.
:::
<!-- %:::% index end %:::% -->
