<!-- %:::% .common h1 begin %:::% -->
# Resumo {.unnumbered}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R/_setup.R"))
```

<!--
Elemento obrigatório, constituído de uma sequência de frases concisas e objetivas, em forma de texto.
Deve apresentar os objetivos, métodos empregados, resultados e conclusões.
O resumo deve ser redigido em parágrafo único, conter no máximo 500 palavras e ser seguido dos termos representativos do conteúdo do trabalho (palavras-chave ou descritores), preferencialmente de acordo com o Vocabulário Controlado do SIBI/USP (UNIVERSIDADE DE SÃO PAULO, 2006). Deve ser precedido da referência do documento e elaborado de acordo com a ABNT NBR 6028 (ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS, 2003).
-->

Vartanian, D. V. ({{< var submitted >}}). _A latitude está associada ao cronotipo?_ [Dissertação de Mestrado, Universidade de São Paulo].

::: {.content-visible when-format="pdf"}
<!-- %:::% foreign-abstract reference begin %:::% -->
Vartanian, D. ({\imprimirdata}). \textit{A latitude está associada ao cronotipo?} [Dissertação de Mestrado, Universidade de São Paulo].
<!-- %:::% foreign-abstract reference end %:::% -->
:::

<!-- %:::% foreign-abstract body begin %:::% -->
Embora avanços significativos tenham sido feitos na compreensão dos ritmos circadianos, pesquisas adicionais com amostras maiores e mais diversas são necessárias para aprofundar o entendimento sobre os fenótipos temporais e sua variabilidade. Esta dissertação examina a relação entre latitude e a expressão do cronotipo humano, investigando se variações na exposição anual à luz solar entre regiões equatoriais e não equatoriais influenciam os fenótipos circadianos. A premissa subjacente sugere que um *zeitgeber* solar mais forte ao equador promove uma maior *entrainment* com o ciclo claro/escuro, potencialmente reduzindo a diversidade fenotípica e favorecendo a matutinidade em populações equatoriais. Para testar essa hipótese, foram analisados dados de $65.824$ indivíduos distribuídos ao longo de um intervalo latitudinal de $33,85026°$ no Brasil. A coleta de dados foi realizada com o Munich ChronoType Questionnaire (MCTQ) durante uma única semana de primavera (15–21 de outubro de 2017), minimizando variações sazonais no fotoperíodo entre as regiões. A análise empregou modelos de regressão aninhados ponderados de acordo com as proporções populacionais no momento da coleta. Contrariando as expectativas, os resultados não indicaram uma relação significativa entre latitude e cronotipo ($f^2$ de Cohen $= 0,0030818242$, $95\% \ \text{IC}[0; 0,0121371208]$), em consonância com achados recentes da área. Todos os procedimentos analíticos, desde os dados brutos até a estimativa do tamanho do efeito, foram conduzidos por meio de métodos totalmente reprodutíveis. Esses achados contribuem para uma compreensão baseada em evidências da regulação dos ritmos circadianos, ao mesmo tempo que desafiam pressupostos estabelecidos na pesquisa em cronobiologia. Ainda que este estudo não refute completamente a hipótese, a associação entre latitude e cronotipo deve permanecer uma questão científica em aberto, em vez de ser considerada um conhecimento consolidado, até que evidências robustas a confirmem.
<!-- %:::% foreign-abstract body end %:::% -->

__Palavras-chave__: Ciência da complexidade. Sistemas complexos. Cronobiologia. Ritmos biológicos. Cronotipos. Fenótipos circadianos. Sono. Entrainment. Latitude. MCTQ.

::: {.content-visible when-format="pdf"}
<!-- %:::% foreign-abstract keywords begin %:::% -->
\hyphenpenalty=100000
\begin{tabular}{p{5cm} p{10.9cm}}
  \textbf{Palavras-chaves}: &  Ciência da complexidade. Sistemas complexos. Cronobiologia. Ritmos biológicos. Cronotipos. Fenótipos circadianos. Sono. Entrainment. Latitude. MCTQ.
\end{tabular}
<!-- %:::% foreign-abstract keywords end %:::% -->
:::
