<!-- %:::% .common h1 begin %:::% -->
# Question, Objective and Hypothesis {#sec-sm-question}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

## Overview

This document provides a detailed outline of the thesis's research question, objective, and hypothesis.

## Question

Every scientific inquiry should be guided by a central question. For this study, the guiding question is:

::: {style="text-align: center; font-size: 1.1em; font-weight: bold; color: #EA7701; padding-top: 1em; padding-bottom: 1em;"}
Is latitude associated with chronotype?
:::

## Objective

The primary objective is to model and test the hypothesis underlying this question within the context of human circadian rhythms, by critically assessing whether there is a meaningful association  between latitude and circadian phenotypes in the Brazilian population.

## Hypothesis

To address the research question, the study employs Popper’s hypothetico-deductive method. A simplified version of this approach can be view as follows:

```{mermaid}
%%| label: fig-mermaid
%%| fig-cap: Simplified schema of Popper’s hypothetico-deductive method.
%%| fig-align: center

flowchart LR
  A(P1) --> B(TT)
  B --> C(EE)
  C --> D(P2)
```

As Popper explained:

> Here $\text{P}_1$, is the **problem** from which we start, $\text{TT}$ (the ‘tentative theory’) is the imaginative conjectural solution which we first reach, for example our first **tentative interpretation**. $\text{EE}$ (‘**error- elimination**’) consists of a severe critical examination of our conjecture, our tentative interpretation: it consists, for example, of the critical use of documentary evidence and, if we have at this early stage more than one conjecture at our disposal, it will also consist of a critical discussion and comparative evaluation of the competing conjectures. $\text{P}_2$ is the problem situation as it emerges from our first critical attempt to solve our problems. It leads up to our second attempt (**and so on**) [@popper1979, p. 164].

As outlined in Chapter 1, the central hypothesis is the following:

::: {#cnj-hypothesis}
### Statment

*Latitude is associated with chronotype distributions*, with populations closer to the equator exhibiting, on average, a shorter or more morning-oriented circadian phenotype compared to those residing near the poles.
:::

This hypothesis is grounded in early discussions in chronobiology and is supported by numerous studies, including: @bohlen1973, @pittendrigh1991, @roenneberg2003, @randler2008, @hut2013, @leocadio-miguel2017, and @randler2017.

To evaluate the hypothesis, the study adopts an improved approach to Null Hypothesis Significance Testing ([NHST](https://en.wikipedia.org/wiki/Statistical_hypothesis_test)), rooted in the original Neyman-Pearson framework for data testing [@neyman1928; @neyman1928a; @perezgonzalez2015]. In a simple way, the hypotheses can be stated as follows:

::: {#cnj-hypothesis-test}
### Data Test – Simple Version

$$
\begin{cases}
\text{H}_{0}: \text{Latitude is not associated with chronotype} \\
\text{H}_{a}: \text{Latitude is associated with chronotype}
\end{cases}
$$
:::

Supplementary Material [-@sec-sm-methods] provides a detailed description of the statistical tests and procedures used to evaluate the hypothesis.
