<!-- %:::% .common h1 begin %:::% -->
# Works and Activities Developed During the Thesis {#sec-sm-works-and-activities}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

During the development of this thesis, several activities have been accomplished. These activities are important to note, as they demonstrate the path taken to arrive at this final document. The following sections detail some of them.

## Courses

The following graduate courses from the University of São Paulo ([USP](https://www5.usp.br/)) were completed during the first year of the master's program.

* 2022/2: [*SCX5000 - Mathematical and Computational Methods I*](https://uspdigital.usp.br/janus/componente/catalogoDisciplinasInicial.jsf?action=3&sgldis=SCX5000) (10 credits) (Concept: **C**);
* 2022/2: [*SCX5002 - Complex Systems I*](https://uspdigital.usp.br/janus/componente/catalogoDisciplinasInicial.jsf?action=3&sgldis=SCX5002) (10 credits) (Concept: **A**);
* 2023/1: [*SCX5001 - Mathematical and Computational Methods II*](https://uspdigital.usp.br/janus/componente/catalogoDisciplinasInicial.jsf?action=3&sgldis=SCX5001) (10 credits) (Concept: **A**);
* 2023/1: [*SCX5017 - Introduction to Data Science*](https://uspdigital.usp.br/janus/componente/catalogoDisciplinasInicial.jsf?action=3&sgldis=SCX5017) (10 credits) (Concept: **A**);
* 2023/1: [*EAH5001 - Pedagogic Preparation*](https://uspdigital.usp.br/janus/componente/catalogoDisciplinasInicial.jsf?action=3&sgldis=EAH5001) (4 credits) (Concept: **A**).

Please note that the unfortunate **C** concept above happened in the same semester when the author broke relations with his former supervisor.

44 discipline credits were completed. An additional 12 special credits, related to an article publication (See @viana-mendes2023), were requested and approved by the Graduate Program Coordination Commission (CCP) in accordance with [program regulations](https://leginf.usp.br/?resolucao=resolucao-copgr-no-7829-de-03-de-outubro-de-2019). In total, 56 credits were earned. A minimum of 50 credits is required for the thesis defense.

## Teaching Internship

Scholarship students under the [Coordination for the Improvement of Higher Education Personnel (CAPES)](https://www.gov.br/capes/) are required to participate in the [Teaching Improvement Program (PAE)](www5.each.usp.br/pae/). This internship occur in the 2º semester of 2023.

The internship responsibilities entailed serving as an Assistant Professor for the undergraduate course [*ACH0042 - Problem-Based Learning II*](https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=ACH0042) at USP. A comprehensive teaching plan was formulated during enrollment in the aforementioned graduate course *EAH5001*, and it is accessible through the following link.

<!-- @vartanian2023b -->

Vartanian, D., Rodrigues Neto, C, & Bernardes, M. E. M. (2023). *Plano de ensino: ACH0042 - Resolução de Problemas II*. <https://doi.org/10.13140/RG.2.2.33335.50086>

## Publications

The following article was published during the development of this thesis.

<!-- @viana-mendes2023 -->

Viana-Mendes, J., Benedito-Silva, A. A., Andrade, M. A. M., **Vartanian, D.**, Gonçalves, B. da S. B., Cipolla-Neto, J., & Pedrazzoli, M. (2023). Actigraphic characterization of sleep and circadian phenotypes of PER3 gene VNTR genotypes. *Chronobiology International*. <https://doi.org/10.1080/07420528.2023.2256858>

## Translations

As a member and package developer of the [rOpenSci Initiative](https://ropensci.org/), the author is actively contributing to the [ongoing translation](https://github.com/ropensci/dev_guide/pull/717) of the [rOpenSci Developer Guide](https://devguide.ropensci.org/) into Portuguese. The aim is to create a more inclusive environment for individuals in Brazil and other Portuguese-speaking countries when developing for the [R programming language](https://www.r-project.org/).

This endeavor is linked to the thesis, as the author's membership in rOpenSci began with the creation of the [{mctq} R package](https://docs.ropensci.org/mctq/) (listed below).

## Conferences

An abstract pertaining to the primary investigation was published and presented on a poster at the [Sao Paulo School of Advanced Science on Ecology of Human Sleep and Biological Rhythms](https://espca.fapesp.br/school/sao_paulo_school_of_advanced_science_on_ecology_of_human_sleep_and_biological_rhythms/101/) organized by the [São Paulo Research Foundation (FAPESP)](https://fapesp.br/en). This international school hosted 100 participants, including students and young researchers, with a diverse representation of 50 individuals from various states within Brazil and an additional 50 from international backgrounds. The event took place from November 16, 2022, to November 26, 2022.

<!-- @vartanian2022a -->

Vartanian, D., & Pedrazzoli, M. (2022). *Ecology of sleep and circadian phenotypes of the Brazilian population* \[Poster\]. São Paulo Research Foundation; São Paulo School of Advanced Science on Ecology of Human Sleep and Biological Rhythms. <https://doi.org/10.13140/RG.2.2.25343.07840>

In the same semester (2022/2), the author also participated in USP's International Symposium on Scientific and Technological Initiation ([SIICUSP](https://prpi.usp.br/siicusp/)) as both an examiner and a participant. As a participant, the author presented a research abstract related to the [{actverse} R package](https://github.com/giperbio/actverse) for actigraphy data analysis, as detailed in @matias2022 and @vartaniang. This project was conceived and developed by the author of this thesis and involved collaboration with two undergraduate students. Notably, this project achieved recognition, securing 2nd place in the category of *Earth and Exact Sciences*.

## Research Compendium

This thesis, along with all the accompanying research, is structured and organized within the research compendium provided below.

<!-- @vartanian2025 -->

Vartanian, D. (2025). *Is latitude associated with chronotype?* [Research compendium]. <https://doi.org/10.17605/OSF.IO/YGKTS>

## Data Plans

This research has also produced and published the following data plan.

<!-- @vartanian2024 -->

Vartanian, D. (2024). *Is latitude associated with chronotype?* [Data Management Plan]. DMPHub. <https://doi.org/10.48321/D1DW8P>

## Softwares

The following R packages, Python package, [Quarto](https://quarto.org/) format (being used to write this thesis), and Espanso package were developed during this thesis.

<!-- @vartaniane -->

Vartanian, D. (n.d.). *{entrainment}: a rule-based model of the 24h light/dark cycle entrainment phenomenon* [Software, Python Package]. <https://github.com/danielvartan/entrainment>

<!-- @vartanianh -->

Vartanian, D[^sm-10-1]. (n.d.). *{mctq}: tools to process the Munich ChronoType Questionnaire (MCTQ)* [Software, R Package]. <https://docs.ropensci.org/mctq> (The package has already surpassed [9,000 downloads](https://danielvartan.shinyapps.io/cran-logs/?package=mctq))

<!-- @vartanianr -->

Vartanian, D. (n.d.). *{brandr}: Brand identity management using brand.yml standard* [Software, R package]. <https://doi.org/10.32614/CRAN.package.brandr>

<!-- @vartanianc -->

Vartanian, D. (n.d.). *{lubritime}: an extension for the lubridate package* [Software, R package]. <https://github.com/danielvartan/lubritime>

<!-- @vartanianq -->

Vartanian, D. (n.d.). *{orbis}: Spatial data analysis tools* [Software, R package]. <https://danielvartan.github.io/orbis>

<!-- @vartanianp -->

Vartanian, D. (n.d.). *{quartor}: Tools for the Quarto publishing system* [Software, R package]. <https://danielvartan.github.io/quartor>

<!-- @vartaniand -->

Vartanian, D. (n.d.). *{lockr}: easily encrypt/decrypt files* [Software, R package]. <https://github.com/danielvartan/lockr>

<!-- @vartanianb -->

Vartanian, D. (n.d.). *{prettycheck}: pretty assertive programming* [Software, R package]. <https://github.com/danielvartan/prettycheck>

<!-- @vartaniang -->

Vartanian, D. (n.d.). *{groomr}: tools to tidy strings and text files* [Software, R package]. <https://github.com/danielvartan/groomr>

<!-- @vartanians -->

Vartanian, D. (n.d.). *{plotr}: Plots made easy* [Software, R package]. <https://danielvartan.github.io/plotr>

<!-- @vartanianf -->

Vartanian, D. (n.d.). *{abnt}: Quarto format for ABNT theses and dissertations* [Software, LaTeX/R]. <https://github.com/danielvartan/abnt>

<!-- @vartaniann -->

Vartanian, D. (n.d.). *HTML color codes in hex and RGB formats for Espanso* [Software, Espanso package]. <https://github.com/danielvartan/groomr>

## Exercises

Some important exercises made public during the development of this thesis are listed below.

<!-- @vartanianm -->

Vartanian, D. (2024). *Illustration of the Lotka–Volterra's predator–prey model*. <https://danielvartan.github.io/lotka-volterra>

<!-- @vartanianj -->

Vartanian, D. (2024). *Illustration of the Lorenz system*. <https://danielvartan.github.io/lorenz-system>

<!-- @vartaniani -->

Vartanian, D. (2024). *Illustration of the SIR model*. <https://danielvartan.github.io/sir>

<!-- @vartaniank -->

Vartanian, D. (2024). *A demonstration of general linear models using penguins*. <https://danielvartan.github.io/linear-models>

<!-- @vartanianl -->

Vartanian, D. (2024). *Demonstrations of the central limit theorem*. <https://danielvartan.github.io/central-limit-theorem>


## Other Projects

The author is also currently working on the development of the project below.

Sales, A. R. V., Vartanian, D., Andrade, M. A. M., Pedrazzoli, M. (2023). *Associations between the duration and quality of sleep in third-trimester pregnant women and the duration of labor* \[Master's project, University of Sao Paulo\]. <https://bit.ly/4fYOWgy>

[^sm-10-1]: The package has already surpassed [9,000 downloads](https://danielvartan.shinyapps.io/cran-logs/?package=mctq).
