<!-- %:::% .common h1 begin %:::% -->
# Works and activities during the development of this thesis
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R/_setup.R"))
```

During the development of this thesis, several activities and results have been accomplished. These activities are important to note, as they demonstrate the path taken to arrive at this final document.

## Courses

The following graduate courses from the University of São Paulo (USP) were completed during the first year of the master's program.

* 2022/2: _SCX5000 - Mathematical and Computational Methods I_ (10 credits) (Concept: __C__);
* 2022/2: _SCX5002 - Complex Systems I_ (10 credits) (Concept: __A__);
* 2023/1: _SCX5001 - Mathematical and Computational Methods II_ (10 credits) (Concept: __A__);
* 2023/1: _SCX5017 - Introduction to Data Science_ (10 credits) (Concept: __A__);
* 2023/1: _EAH5001 - Pedagogic Preparation_ (4 credits) (Concept: __A__).

Please note that the unfortunate __C__ concept above happened in the same semester when the author broke relations with his former supervisor (_Mario Pedrazzoli_).

44 discipline credits were completed by this thesis publication date. An additional 12 special credits, related to an article publication (see @viana-mendes2023), were requested and approved by the Graduate Program Coordination Commission (CCP) in accordance with [program regulations](https://leginf.usp.br/?resolucao=resolucao-copgr-no-7829-de-03-de-outubro-de-2019). In total, 56 credits were earned. A minimum of 50 credits is required for the thesis defense.

## Teaching internship

Scholarship students under the [Coordination for the Improvement of Higher Education Personnel (CAPES)](https://www.gov.br/capes/) are required to participate in the [Teaching Improvement Program (PAE)](www5.each.usp.br/pae/). This internship occur in the 2º semester of 2023.

The internship responsibilities entailed serving as an Assistant Professor for the undergraduate course _ACH0042 - Problem-Based Learning II_ at USP. A comprehensive teaching plan [@vartanian2023e] was formulated during enrollment in the aforementioned graduate course _EAH5001_, and it is accessible through the following link.

```{=latex}
\smallskip
```

\noindent Vartanian, D., Rodrigues Neto, C, & Bernardes, M. E. M. (2023). _Plano de ensino: ACH0042 - Resolução de Problemas II_. <https://doi.org/10.13140/RG.2.2.33335.50086>

## Publications

The following article [@viana-mendes2023] was published during the development of this thesis.

```{=latex}
\smallskip
```

\noindent Viana-Mendes, J., Benedito-Silva, A. A., Andrade, M. A. M., __Vartanian, D.__, Gonçalves, B. da S. B., Cipolla-Neto, J., & Pedrazzoli, M. (2023). Actigraphic characterization of sleep and circadian phenotypes of PER3 gene VNTR genotypes. _Chronobiology International_. <https://doi.org/10.1080/07420528.2023.2256858>

## Translations

As a member and package developer of the [rOpenSci Initiative](https://ropensci.org/) (based in Berkeley, CA), the author is actively contributing to the [ongoing translation](https://github.com/ropensci/dev_guide/pull/717) of the [rOpenSci Developer Guide](https://devguide.ropensci.org/) into Portuguese. The aim is to create a more inclusive environment for individuals in Brazil and other Portuguese-speaking countries when developing for the [R programming language](https://www.r-project.org/).

This endeavor is linked to the thesis, as the author's membership in rOpenSci began with the creation of the [{mctq} R package](https://docs.ropensci.org/mctq/) (listed below).

## Conferences

An abstract pertaining to the primary investigation was published and presented on a poster at the [Sao Paulo School of Advanced Science on Ecology of Human Sleep and Biological Rhythms](https://espca.fapesp.br/school/sao_paulo_school_of_advanced_science_on_ecology_of_human_sleep_and_biological_rhythms/101/) organized by the [São Paulo Research Foundation (FAPESP)](https://fapesp.br/en). This international school hosted 100 participants, including students and young researchers, with a diverse representation of 50 individuals from various states within Brazil and an additional 50 from international backgrounds. The event took place from November 16, 2022, to November 26, 2022.

```{=latex}
\smallskip
```

<!-- @vartanian2022a -->

\noindent Vartanian, D., & Pedrazzoli, M. (2022). _Ecology of sleep and circadian phenotypes of the Brazilian population_ \[Poster\]. São Paulo Research Foundation; São Paulo School of Advanced Science on Ecology of Human Sleep and Biological Rhythms. <https://doi.org/10.13140/RG.2.2.25343.07840>

```{=latex}
\smallskip
```

In the same semester (2022/2), the author also participated in USP's International Symposium on Scientific and Technological Initiation (SIICUSP) as both an examiner and a participant. As a participant, the author presented a research abstract related to the [{actverse} R package](https://github.com/giperbio/actverse) for actigraphy data analysis, as detailed in @matias2022 and @vartanian2022b. This project was conceived and developed by the author of this thesis and involved collaboration with two undergraduate students. Notably, this project achieved recognition, securing 2nd place in the category of _Earth and Exact Sciences_.

## Research compendia

This thesis, along with all the accompanying research, is structured and organized within the research compendium provided below.

```{=latex}
\smallskip
```

<!-- @vartanian2024 -->

\noindent Vartanian, D. (2023). _Is latitude associated with the regulation of circadian rhythms in humans?_ [Research compendium]. <https://danielvartan.github.io/mastersthesis/>

## Data plans

This research has also produced and published the following open data model and data plan.

```{=latex}
\smallskip
```

<!-- @vartanian2023b -->

\noindent Vartanian, D. (2023). _Is latitude associated with the regulation of circadian rhythms in humans?_ [Data Management Plan]. DMPHub. <https://doi.org/10.48321/D1DW8P>

## Softwares

The following R packages, [Quarto](https://quarto.org/) format (being used to write this thesis), and Python package were developed in relation with this thesis.

```{=latex}
\smallskip
```

<!-- @vartanian2022 -->

\noindent Vartanian, D. (2022). _{entrainment}: a rule-based model of the 24h light/dark cycle entrainment phenomenon_ [Software, Python Package]. <https://github.com/danielvartan/entrainment>

```{=latex}
\microskip
```

<!-- @vartanian2023 -->

\noindent Vartanian, D. (2023). _{mctq}: tools to process the Munich ChronoType Questionnaire (MCTQ)_ [Software, R Package v0.3.2]. <https://docs.ropensci.org/mctq/>

```{=latex}
\microskip
```

<!-- @vartanian2023b -->

\noindent Vartanian, D. (2023). _{lockr}: easily encrypt/decrypt files_ [Software, R package v0.3.0]. <https://github.com/danielvartan/lockr>

```{=latex}
\microskip
```

<!-- @vartanian2023c -->

\noindent Vartanian, D. (2023). _{lubritime}: an extension for the lubridate package_ [Software, R package]. <https://github.com/danielvartan/lubritime>

```{=latex}
\microskip
```

<!-- @vartanian2023a -->

\noindent Vartanian, D. (2023). _{abnt}: Quarto format for ABNT theses and dissertations_ [Software, LaTeX/R format, v0.3.0]. <https://github.com/danielvartan/abnt/>

## Other projects

The author is also currently working on the development of the project below.

```{=latex}
\smallskip
```

\noindent Sales, A. R. V., Vartanian, D., Andrade, M. A. M., Pedrazzoli, M. (2023). _Associations between the duration and quality of sleep in third-trimester pregnant women and the duration of labor_ \[PhD project, University of Sao Paulo\]. <https://bit.ly/3S6O0MB>
