<!-- %:::% .common h1 begin %:::% -->
# Abstract {.unnumbered}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R/_setup.R"))
```

Vartanian, D. (`r env_vars[["submitted"]]`). *`r env_vars[["title"]] |> stringr::str_to_sentence()`* [`r env_vars[["academic-title"]]`'s `r env_vars[["type-of-work"]]`, `r env_vars[["university"]]`]. [https://doi.org/10.17605/OSF.IO/YGKTS](https://doi.org/10.17605/OSF.IO/YGKTS)

::: {.content-visible when-format="pdf"}
<!-- %:::% vernacular-abstract reference begin %:::% -->
Vartanian, D. ({\imprimirdata}). \textit{\imprimirtitulo} [{\imprimirtipodetituloacademico}'s {\imprimirtipotrabalho}, {\imprimiruniversidade}].
<!-- %:::% vernacular-abstract reference end %:::% -->
:::

<!-- %:::% vernacular-abstract body begin %:::% -->
Although significant progress has been made in understanding circadian rhythms, further research with larger and more diverse samples is needed to deepen our understanding of temporal phenotypes and their variability. This thesis examines the relationship between latitude and human chronotype expression, investigating whether variations in annual sunlight exposure between equatorial and non-equatorial regions influence circadian phenotypes. The underlying premise suggests that a stronger solar zeitgeber near the equator should promote greater entrainment to the light/dark cycle, potentially reducing phenotype diversity and favoring morningness in equatorial populations. To test this hypothesis, data from $65,824$ individuals distributed across a $33.850°$ latitute range in Brazil were analyzed. Data collection employed the Munich ChronoType Questionnaire (MCTQ) during a single spring week (October 15–21, 2017), minimizing seasonal variations in photoperiod across regions. The analysis employed nested regression models weighted according to population proportions at the time of data collection. Contrary to expectations, results revealed no meaningful relationship between latitude and chronotype (Cohen's $f^2 = 0.00308$, $95\% \ \text{CI}[0, 0.01214]$), consistent with recent findings in the field. All analytical procedures, from raw data processing through effect size estimation, were conducted using reproducible methods. These findings contribute to our evidence-based understanding of circadian rhythm regulation while challenging established assumptions in chronobiology research. While this study does not refute the hypothesis outright, the association between latitude and chronotype should remain an open scientific question rather than settled knowledge until robust evidence confirms it.
<!-- %:::% vernacular-abstract body end %:::% -->

<!-- The results highlight the complex nature of the human chronotype and emphasize the importance of investigating alternative factors that may influence them. -->

**Keywords**: {{< var keyword >}}

::: {.content-visible when-format="pdf"}
<!-- %:::% vernacular-abstract keywords begin %:::% -->
\hyphenpenalty=100000
\begin{tabular}{p{2.5cm} p{13.4cm}}
  \textbf{Keywords}: & Complexity science. Complex systems. Chronobiology. Biological rhythms. Chronotypes. Circadian phenotypes. Sleep. Entrainment. Latitude. MCTQ.
\end{tabular}
<!-- %:::% vernacular-abstract keywords end %:::% -->
:::
