{
  "hash": "f099eb3e5c790f16aeab7fa8985022e4",
  "result": {
    "markdown": "# Appendice: Chapter 6 supplemental material\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note}\nYou are reading the work-in-progress of this thesis. This chapter should be readable but is currently undergoing final polishing.\n:::\n\n\n\n<!--\n## Some references\n\nSee @allen1997; @bussab1988; @degroot2012; @hair2019; @johnson2013; @kuhn2022; @dudek2020; @dalpiaz; @fox2016 .\n\nOther references :\n\n* <https://olsrr.rsquaredacademy.com>\n* <https://www.r-bloggers.com/2021/05/how-to-compare-nested-models-in-r/>\n* <https://www.r-bloggers.com/2022/10/box-cox-transformation-in-r/>\n* <https://online.stat.psu.edu/stat501/>\n-->\n\n## Hypothesis\n\n> Populations residing near the equator (latitude 0°) exhibit, on average, a shorter/morning circadian phenotype when compared to populations residing near the poles of the planet [@horzum2015; @hut2013; @leocadio-miguel2017; @leocadio-miguel2014; @pittendrigh1991; @randler2017].\n\nThe study hypothesis was tested using nested models of multiple linear regressions. The main idea of nested models is to verify the effect of the inclusion of one or more predictors in the model variance explanation (i.e., the $\\text{R}^{2}$) [@allen1997]. This can be made by creating a restricted model and then comparing it with a full model. Hence, the hypothesis can be schematized as follows.\n\n$$\n\\begin{cases}\n\\text{H}_{0}: \\text{R}^{2}_{\\text{res}} >= \\text{R}^{2}_{\\text{full}} \\\\\n\\text{H}_{a}: \\text{R}^{2}_{\\text{res}} < \\text{R}^{2}_{\\text{full}}\n\\end{cases}\n$$\n\nThe general equation for the F-test [@allen1997, pp. 113] :\n\n$$\n\\text{F} = \\cfrac{\\text{R}^{2}_{F} - \\text{R}^{2}_{R} / (k_{F} - k_{R})}{(1 - \\text{R}^{2}_{F}) / (\\text{N} - k_{F} - 1)}\n$$\n\nWhere:\n\n* $\\text{R}^{2}_{F}$ = Coefficient of determination for the __full__ model\n* $\\text{R}^{2}_{R}$ = Coefficient of determination for the __restricted__ model\n* $k_{F}$ = Number of independent variables in the full model\n* $k_{R}$ = Number of independent variables in the restricted model\n* $\\text{N}$ = Number of observations in the sample\n\n$$\n\\text{F} = \\cfrac{\\text{Additional Var. Explained} / \\text{Additional d.f. Expended}}{\\text{Var. unexplained} / \\text{d.f. Remaining}}\n$$\n\n## Assumptions\n\nSee @degroot2012 [pp. 736-738] to learn more.\n\n::: {.callout-warning}\n__The predictor is known__. Either the vectors $z_{1}, \\dots , z_{n}$ are known ahead of time, or they are the observed values of random vectors $Z_{1}, \\dots , Z_{n}$ on whose values we condition before computing the joint distribution of ($Y_{1}, \\dots , Y_{n}$).\n:::\n\n::: {.callout-warning}\n__Normality__. For $i = 1, \\dots, n$, the conditional distribution of $Y_{i}$ given the vectors $z_{1}, \\dots , z_{n}$ is a normal distribution (__normality assumption__).\n:::\n\n::: {.callout-warning}\n__Linear mean__. There is a vector of parameters  $\\beta = (\\beta_{0}, \\dots, \\beta_{p - 1})$ such that the conditional mean of $Y_{i}$ given the values $z_{1}, \\dots , z_{n}$ has the form\n\n$$\nz_{i0} \\beta_{0} + z_{i1} \\beta_{1} + \\cdots + z_{ip - 1} \\beta_{p - 1}\n$$\n\nfor $i = 1, \\dots, n$ (__zero error mean assumption__).\n:::\n\n::: {.callout-warning}\n__Common variance__. The observations $Y_{1}, \\dots , Y_{n}$ have the same variance $\\sigma^{2}$ (__homoscedasticity assumption__).\n:::\n\n::: {.callout-warning}\n__Independence__. The random variables $Y_{1}, \\dots , Y_{n}$ are independent given the observed $z_{1}, \\dots , z_{n}$ (__independent errors assumption__).\n:::\n\n## Data preparation\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(dplyr)\n# library(here)\nlibrary(targets)\n# library(tidyr)\n\nsource(here::here(\"R/utils.R\"))\n\nutc_minus_3_states <- c(\n  \"Amapá\", \"Pará\", \"Maranhão\", \"Tocantins\", \"Piauí\", \"Ceará\",\n  \"Rio Grande do Norte\", \"Paraíba\", \"Pernambuco\", \"Alagoas\", \"Sergipe\",\n  \"Bahia\", \"Distrito Federal\", \"Goiás\", \"Minas Gerais\", \"Espírito Santo\",\n  \"Rio de Janeiro\", \"São Paulo\", \"Paraná\", \"Santa Catarina\",\n  \"Rio Grande do Sul\"\n)\n\ndata <- \n  targets::tar_read(\"geocoded_data\", store = here::here(\"_targets\")) |>\n  dplyr::filter(state %in% utc_minus_3_states) |>\n  dplyr::select(msf_sc, age, sex, state, latitude, longitude) |>\n  dplyr::mutate(msf_sc = transform_time(msf_sc)) |>\n  tidyr::drop_na(msf_sc, age, sex, latitude)\n```\n:::\n\n\n\n## Restricted model\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(MASS)\n\nbox_cox <- MASS::boxcox(msf_sc ~ age + sex, data = data)\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-4-1.png)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nlambda <- box_cox$x[which.max(box_cox$y)]\n\nlambda\n#> [1] -1.1111\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(stats)\n\nres_model <- stats::lm(\n  ((msf_sc^lambda - 1) / lambda) ~ age + sex, data = data\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(broom)\n\nbroom::tidy(res_model)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r|r}\n\\hline\nterm & estimate & std.error & statistic & p.value\\\\\n\\hline\n(Intercept) & 0.9 & 0 & 513579298.250 & 0\\\\\n\\hline\nage & 0.0 & 0 & -65.128 & 0\\\\\n\\hline\nsexMale & 0.0 & 0 & 13.020 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(broom)\n# library(dplyr)\n# library(tidyr)\n\nbroom::glance(res_model) |> tidyr::pivot_longer(cols = dplyr::everything())\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r}\n\\hline\nname & value\\\\\n\\hline\nr.squared & 0.054\\\\\n\\hline\nadj.r.squared & 0.054\\\\\n\\hline\nsigma & 0.000\\\\\n\\hline\nstatistic & 2178.876\\\\\n\\hline\np.value & 0.000\\\\\n\\hline\ndf & 2.000\\\\\n\\hline\nlogLik & 1106194.897\\\\\n\\hline\nAIC & -2212381.794\\\\\n\\hline\nBIC & -2212344.801\\\\\n\\hline\ndeviance & 0.000\\\\\n\\hline\ndf.residual & 76741.000\\\\\n\\hline\nnobs & 76744.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\n# res_model |> olsrr::ols_regress()\nres_model |> summary()\n#> \n#> Call:\n#> stats::lm(formula = ((msf_sc^lambda - 1)/lambda) ~ age + sex, \n#>     data = data)\n#> \n#> Residuals:\n#>           Min            1Q        Median            3Q           Max \n#> -0.0000004859 -0.0000000911 -0.0000000031  0.0000000916  0.0000004204 \n#> \n#> Coefficients:\n#>                     Estimate       Std. Error     t value Pr(>|t|)    \n#> (Intercept)  0.8999976603602  0.0000000017524 513579298.2   <2e-16 ***\n#> age         -0.0000000033812  0.0000000000519       -65.1   <2e-16 ***\n#> sexMale      0.0000000132309  0.0000000010162        13.0   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.000000133 on 76741 degrees of freedom\n#> Multiple R-squared:  0.0537,\tAdjusted R-squared:  0.0537 \n#> F-statistic: 2.18e+03 on 2 and 76741 DF,  p-value: <2e-16\n```\n:::\n\n\n\n### Residual diagnostics\n\nNormality and zero mean error assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(stats)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\nres_model |>\n  stats::residuals() |>\n  stats_sum(print = FALSE) |>\n  list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 76744\\\\\n\\hline\nn\\_rm\\_na & 76744\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 6.60699976667332e-23\\\\\n\\hline\nvar & 0.0000000000000176852866826985\\\\\n\\hline\nsd & 0.000000132986039427823\\\\\n\\hline\nmin & -0.000000485865195534305\\\\\n\\hline\nq\\_1 & -0.0000000911138016567908\\\\\n\\hline\nmedian & -0.00000000313530324787135\\\\\n\\hline\nq\\_3 & 0.000000091553820345483\\\\\n\\hline\nmax & 0.000000420368932360539\\\\\n\\hline\niqr & 0.000000182667622002274\\\\\n\\hline\nskewness & -0.0105262146639209\\\\\n\\hline\nkurtosis & 2.82813923301771\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# See `?moments::agostino.test` & `?fBasics::dagoTest()` to learn more.\n\n# library(fBasics)\n# library(moments)\n\nsource(here::here(\"R/normality_sum.R\"))\n\nres_model |>\n  stats::residuals() |>\n  normality_sum()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r}\n\\hline\ntest & p\\_value\\\\\n\\hline\nAnderson-Darling & 0.000\\\\\n\\hline\nBonett-Seier & 0.000\\\\\n\\hline\nCramer-von Mises & 0.000\\\\\n\\hline\nD'Agostino Omnibus Test & NA\\\\\n\\hline\nD'Agostino Skewness Test & 0.234\\\\\n\\hline\nD'Agostino Kurtosis Test & NA\\\\\n\\hline\nJarque–Bera & 0.000\\\\\n\\hline\nLilliefors (K-S) & 0.000\\\\\n\\hline\nPearson chi-square & 0.000\\\\\n\\hline\nShapiro-Francia & NA\\\\\n\\hline\nShapiro-Wilk & NA\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\nCorrelation between observed residuals and expected residuals under normality.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nres_model |> olsrr::ols_test_correlation()\n#> [1] 0.99929\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(cowplot)\n# library(olsrr)\n# library(stats)\n\nsource(here::here(\"R/test_normality.R\"))\n\n# res_model |> olsrr::ols_plot_resid_qq()\n\nqq_plot <- res_model |> \n  stats::residuals() |>\n  plot_qq(print = FALSE)\n\nhist_plot <- res_model |>\n  stats::residuals() |>\n  plot_hist(print = FALSE)\n\ncowplot::plot_grid(hist_plot, qq_plot, ncol = 2, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-12-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\n# Linear mean assumption\n\nres_model |> olsrr::ols_plot_resid_fit()\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-13-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nres_model |> plot(3)\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-14-1.png)\n:::\n:::\n\n\n\n### Heteroskedasticity\n\nHomoscedasticity assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\n# \"It test whether variance of errors from a regression is dependent on the values of a independent variable.\"\n\nres_model |> olsrr::ols_test_breusch_pagan()\n#> \n#>  Breusch Pagan Test for Heteroskedasticity\n#>  -----------------------------------------\n#>  Ho: the variance is constant            \n#>  Ha: the variance is not constant        \n#> \n#>                           Data                           \n#>  --------------------------------------------------------\n#>  Response : ((msf_sc^lambda - 1)/lambda) \n#>  Variables: fitted values of ((msf_sc^lambda - 1)/lambda) \n#> \n#>         Test Summary          \n#>  -----------------------------\n#>  DF            =    1 \n#>  Chi2          =    70149.3586 \n#>  Prob > Chi2   =    0.0000\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nres_model |> olsrr::ols_test_score()\n#> \n#>  Score Test for Heteroskedasticity\n#>  ---------------------------------\n#>  Ho: Variance is homogenous\n#>  Ha: Variance is not homogenous\n#> \n#>  Variables: fitted values of ((msf_sc^lambda - 1)/lambda) \n#> \n#>       Test Summary       \n#>  ------------------------\n#>  DF            =    1 \n#>  Chi2          =    0.000 \n#>  Prob > Chi2   =    1.000\n```\n:::\n\n\n\n### Collinearity diagnostics\n\nIndependence assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nres_model |> olsrr::ols_coll_diag()\n#> Tolerance and Variance Inflation Factor\n#> ---------------------------------------\n#>   Variables Tolerance    VIF\n#> 1       age    0.9988 1.0012\n#> 2   sexMale    0.9988 1.0012\n#> \n#> \n#> Eigenvalue and Condition Index\n#> ------------------------------\n#>   Eigenvalue Condition Index intercept      age   sexMale\n#> 1   2.422418          1.0000  0.011753 0.011936 0.0669897\n#> 2   0.538450          2.1211  0.015824 0.018848 0.9280439\n#> 3   0.039132          7.8679  0.972423 0.969216 0.0049664\n```\n:::\n\n\n\nThe variance inflation factor measures how much the behavior (variance) of an independent variable is influenced, or inflated, by its interaction/correlation with the other independent variables (e.g., VIF equal to 1 = variables are not correlated).\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(car)\n\nres_model |> car::vif()\n#>    age    sex \n#> 1.0012 1.0012\n```\n:::\n\n\n\n### Measures of influence\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nres_model |> olsrr::ols_plot_resid_lev()\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-19-1.png)\n:::\n:::\n\n\n\n## Full model\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(MASS)\n\nbox_cox <- MASS::boxcox(\n  msf_sc ~ age + sex + latitude, data = data\n  )\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-20-1.png)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n\nbox_cox$x[which.max(box_cox$y)] # lambda\n#> [1] -1.1515\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlambda # The same lambda of the restricted model\n#> [1] -1.1111\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(stats)\n\nfull_model <- stats::lm(\n  ((msf_sc^lambda - 1) / lambda) ~ age + sex + latitude, \n  data = data\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(broom)\n\n# ?broom::tidy.lm\nbroom::tidy(full_model)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r|r}\n\\hline\nterm & estimate & std.error & statistic & p.value\\\\\n\\hline\n(Intercept) & 0.9 & 0 & 391908052.847 & 0\\\\\n\\hline\nage & 0.0 & 0 & -66.928 & 0\\\\\n\\hline\nsexMale & 0.0 & 0 & 13.558 & 0\\\\\n\\hline\nlatitude & 0.0 & 0 & -23.852 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(broom)\n# library(dplyr)\n# library(tidyr)\n\n# ?broom::glance.lm\nbroom::glance(full_model) |>\n  tidyr::pivot_longer(cols = dplyr::everything())\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r}\n\\hline\nname & value\\\\\n\\hline\nr.squared & 0.061\\\\\n\\hline\nadj.r.squared & 0.061\\\\\n\\hline\nsigma & 0.000\\\\\n\\hline\nstatistic & 1652.979\\\\\n\\hline\np.value & 0.000\\\\\n\\hline\ndf & 3.000\\\\\n\\hline\nlogLik & 1106478.331\\\\\n\\hline\nAIC & -2212946.661\\\\\n\\hline\nBIC & -2212900.420\\\\\n\\hline\ndeviance & 0.000\\\\\n\\hline\ndf.residual & 76740.000\\\\\n\\hline\nnobs & 76744.000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# full_model |> olsrr::ols_regress()\nfull_model |> summary()\n#> \n#> Call:\n#> stats::lm(formula = ((msf_sc^lambda - 1)/lambda) ~ age + sex + \n#>     latitude, data = data)\n#> \n#> Residuals:\n#>           Min            1Q        Median            3Q           Max \n#> -0.0000004874 -0.0000000911 -0.0000000034  0.0000000912  0.0000004328 \n#> \n#> Coefficients:\n#>                     Estimate       Std. Error     t value Pr(>|t|)    \n#> (Intercept)  0.8999976247783  0.0000000022965 391908052.9   <2e-16 ***\n#> age         -0.0000000034710  0.0000000000519       -66.9   <2e-16 ***\n#> sexMale      0.0000000137296  0.0000000010127        13.6   <2e-16 ***\n#> latitude    -0.0000000018222  0.0000000000764       -23.9   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.000000132 on 76740 degrees of freedom\n#> Multiple R-squared:  0.0607,\tAdjusted R-squared:  0.0607 \n#> F-statistic: 1.65e+03 on 3 and 76740 DF,  p-value: <2e-16\n```\n:::\n\n\n\n### Residual diagnostics\n\nNormality and zero mean error assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(stats)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\nfull_model |>\n  stats::residuals() |>\n  stats_sum(print = FALSE) |> \n  list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 76744\\\\\n\\hline\nn\\_rm\\_na & 76744\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 4.85272564733669e-24\\\\\n\\hline\nvar & 0.0000000000000175551361304561\\\\\n\\hline\nsd & 0.00000013249579665203\\\\\n\\hline\nmin & -0.000000487410752460545\\\\\n\\hline\nq\\_1 & -0.0000000910649425186321\\\\\n\\hline\nmedian & -0.000000003374344652286\\\\\n\\hline\nq\\_3 & 0.0000000911899588839585\\\\\n\\hline\nmax & 0.000000432826012898983\\\\\n\\hline\niqr & 0.000000182254901402591\\\\\n\\hline\nskewness & 0.000655994107765645\\\\\n\\hline\nkurtosis & 2.82688323293117\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(stats)\n\nsource(here::here(\"R/normality_sum.R\"))\n\nfull_model |>\n  stats::residuals() |>\n  normality_sum()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r}\n\\hline\ntest & p\\_value\\\\\n\\hline\nAnderson-Darling & 0.000\\\\\n\\hline\nBonett-Seier & 0.000\\\\\n\\hline\nCramer-von Mises & 0.000\\\\\n\\hline\nD'Agostino Omnibus Test & NA\\\\\n\\hline\nD'Agostino Skewness Test & 0.941\\\\\n\\hline\nD'Agostino Kurtosis Test & NA\\\\\n\\hline\nJarque–Bera & 0.000\\\\\n\\hline\nLilliefors (K-S) & 0.000\\\\\n\\hline\nPearson chi-square & 0.000\\\\\n\\hline\nShapiro-Francia & NA\\\\\n\\hline\nShapiro-Wilk & NA\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\nCorrelation between observed residuals and expected residuals under normality.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nfull_model |> olsrr::ols_test_correlation()\n#> [1] 0.99929\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(cowplot)\n# library(olsrr)\n# library(stats)\n\nsource(here::here(\"R/test_normality.R\"))\n\n# full_model |> olsrr::ols_plot_resid_qq()\n\nhist_plot <- full_model |>\n  stats::residuals() |>\n  plot_hist(print = FALSE)\n\nqq_plot <- full_model |> \n  stats::residuals() |>\n  plot_qq(print = FALSE)\n\ncowplot::plot_grid(hist_plot, qq_plot, ncol = 2, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-29-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nfull_model |> olsrr::ols_plot_resid_fit()\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-30-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfull_model |> plot(3)\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-31-1.png)\n:::\n:::\n\n\n\n### Heteroskedasticity\n\nHomoscedasticity assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nfull_model |> olsrr::ols_test_breusch_pagan()\n#> \n#>  Breusch Pagan Test for Heteroskedasticity\n#>  -----------------------------------------\n#>  Ho: the variance is constant            \n#>  Ha: the variance is not constant        \n#> \n#>                           Data                           \n#>  --------------------------------------------------------\n#>  Response : ((msf_sc^lambda - 1)/lambda) \n#>  Variables: fitted values of ((msf_sc^lambda - 1)/lambda) \n#> \n#>         Test Summary          \n#>  -----------------------------\n#>  DF            =    1 \n#>  Chi2          =    70101.1634 \n#>  Prob > Chi2   =    0.0000\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nfull_model |> olsrr::ols_test_score()\n#> \n#>  Score Test for Heteroskedasticity\n#>  ---------------------------------\n#>  Ho: Variance is homogenous\n#>  Ha: Variance is not homogenous\n#> \n#>  Variables: fitted values of ((msf_sc^lambda - 1)/lambda) \n#> \n#>       Test Summary       \n#>  ------------------------\n#>  DF            =    1 \n#>  Chi2          =    0.000 \n#>  Prob > Chi2   =    1.000\n```\n:::\n\n\n\n### Collinearity diagnostics\n\nIndependence assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nfull_model |> olsrr::ols_coll_diag()\n#> Tolerance and Variance Inflation Factor\n#> ---------------------------------------\n#>   Variables Tolerance    VIF\n#> 1       age   0.99354 1.0065\n#> 2   sexMale   0.99838 1.0016\n#> 3  latitude   0.99441 1.0056\n#> \n#> \n#> Eigenvalue and Condition Index\n#> ------------------------------\n#>   Eigenvalue Condition Index  intercept       age   sexMale  latitude\n#> 1   3.312504          1.0000 0.00377395 0.0064918 0.0304493 0.0068553\n#> 2   0.584652          2.3803 0.00328127 0.0064143 0.9588857 0.0083393\n#> 3   0.073700          6.7042 0.00040414 0.5063551 0.0023826 0.5659326\n#> 4   0.029145         10.6609 0.99254063 0.4807389 0.0082824 0.4188728\n```\n:::\n\n\n\nThe variance inflation factor measures how much the behavior (variance) of an independent variable is influenced, or inflated, by its interaction/correlation with the other independent variables (e.g., VIF equal to 1 = variables are not correlated).\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(car)\n\nfull_model |> car::vif()\n#>      age      sex latitude \n#>   1.0065   1.0016   1.0056\n```\n:::\n\n\n\n### Measures of influence\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(olsrr)\n\nfull_model |> olsrr::ols_plot_resid_lev()\n```\n\n::: {.cell-output-display}\n![](appendice-ch-6_files/figure-pdf/unnamed-chunk-36-1.png)\n:::\n:::\n\n\n\n\n## Nested regression models test\n\n$$\n\\begin{cases}\n\\text{H}_{0}: \\text{R}^{2}_{\\text{res}} >= \\text{R}^{2}_{\\text{full}} \\\\\n\\text{H}_{a}: \\text{R}^{2}_{\\text{res}} < \\text{R}^{2}_{\\text{full}}\n\\end{cases}\n$$\n\n$$\n\\text{F} = \\cfrac{\\text{R}^{2}_{F} - \\text{R}^{2}_{R} / (k_{F} - k_{R})}{(1 - \\text{R}^{2}_{F}) / (\\text{N} - k_{F} - 1)}\n$$\n\n$$\n\\text{F} = \\cfrac{\\text{Additional Var. Explained} / \\text{Additional d.f. Expended}}{\\text{Var. unexplained} / \\text{d.f. Remaining}}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(dplyr)\n# library(here)\n\nsource(here::here(\"R/utils-stats.R\"))\n\ndplyr::tibble(\n  name = c(\"r_squared_res\", \"r_squared_full\", \"diff\"),\n  value = c(\n  r_squared(res_model), r_squared(full_model), \n  r_squared(full_model) - r_squared(res_model)\n  )\n)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r}\n\\hline\nname & value\\\\\n\\hline\nr\\_squared\\_res & 0.054\\\\\n\\hline\nr\\_squared\\_full & 0.061\\\\\n\\hline\ndiff & 0.007\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(stats)\n\nstats::anova(res_model, full_model)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{r|r|r|r|r|r}\n\\hline\nRes.Df & RSS & Df & Sum of Sq & F & Pr(>F)\\\\\n\\hline\n76741 & 0 & NA & NA & NA & NA\\\\\n\\hline\n76740 & 0 & 1 & 0 & 568.94 & 0\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(stats)\n# library(here)\n\nsource(here::here(\"R/utils-stats.R\"))\n\nn <- nrow(data)\nk_res <- length(stats::coefficients(res_model)) - 1\nk_full <- length(stats::coefficients(full_model)) - 1\n\n((r_squared(full_model) - r_squared(res_model)) / (k_full - k_res)) / ((1 - r_squared(full_model)) / (n  - k_full - 1))\n#> [1] 568.94\n```\n:::\n\n\n\n$$\nf^{2} = \\cfrac{\\text{R}^{2}_{F} - \\text{R}^{2}_{R}}{1 - \\text{R}^{2}_{F}}\n$$\n\n$$\nf^{2} = \\cfrac{\\text{Additional Var. Explained}}{\\text{Var. unexplained}}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n\nsource(here::here(\"R/cohens_f_squared.R\"))\nsource(here::here(\"R/utils-stats.R\"))\n\ncohens_f_squared_summary(\n  adj_r_squared(res_model), \n  adj_r_squared(full_model)\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nf\\_squared & 0.00740068896515648\\\\\n\\hline\neffect\\_size & Negligible\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\n## Group test\n\n$$\n\\begin{cases}\n\\text{H}_{0}: \\text{MSF}^{0^{o}}_{\\text{sc}} >= \\text{MSF}^{30^{o}}_{\\text{sc}} \\\\\n\\text{H}_{a}: \\text{MSF}^{0^{o}}_{\\text{sc}} < \\text{MSF}^{30^{o}}_{\\text{sc}}\n\\end{cases}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(dplyr)\n# library(here)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\ngroup_1 <- \"Amapá\" # Boa vista (0° 2′ 18.84″ N, 51° 3′ 59.1″ W)\n\nmsf_sc_group_1 <- \n  data |>\n  dplyr::filter(state == group_1) |>\n  magrittr::extract2(\"msf_sc\")\n\nstats_sum_group_1 <- \n  data |> \n  dplyr::filter(state == group_1) |>\n  magrittr::extract2(\"msf_sc\") |> \n  stats_sum(print = FALSE)\n\nstats_sum_group_1 |> list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 113\\\\\n\\hline\nn\\_rm\\_na & 113\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 103564.475347661\\\\\n\\hline\nvar & 28720417.6933099\\\\\n\\hline\nsd & 5359.14337308771\\\\\n\\hline\nmin & 92100\\\\\n\\hline\nq\\_1 & 99000\\\\\n\\hline\nmedian & 104164.285714286\\\\\n\\hline\nq\\_3 & 107142.857142857\\\\\n\\hline\nmax & 114450\\\\\n\\hline\niqr & 8142.85714285714\\\\\n\\hline\nskewness & -0.0419134073448402\\\\\n\\hline\nkurtosis & 2.19330502090315\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(dplyr)\n# library(here)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\ngroup_2 <- \"Rio Grande do Sul\" # Porto Alegre (30° 01' 58\" S, 51° 13' 48\" O)\n\nmsf_sc_group_2 <- data |>\n  dplyr::filter(state == group_2) |>\n  magrittr::extract2(\"msf_sc\")\n\nstats_sum_group_2 <- \n  data |> \n  dplyr::filter(state == group_2) |>\n  magrittr::extract2(\"msf_sc\") |> \n  stats_sum(print = FALSE)\n\nstats_sum_group_2 |> list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 4097\\\\\n\\hline\nn\\_rm\\_na & 4097\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 103651.485407441\\\\\n\\hline\nvar & 26397872.5737977\\\\\n\\hline\nsd & 5137.88600241361\\\\\n\\hline\nmin & 88092.8571428571\\\\\n\\hline\nq\\_1 & 99857.1428571429\\\\\n\\hline\nmedian & 103328.571428571\\\\\n\\hline\nq\\_3 & 107057.142857143\\\\\n\\hline\nmax & 117064.285714286\\\\\n\\hline\niqr & 7200\\\\\n\\hline\nskewness & 0.263604552812467\\\\\n\\hline\nkurtosis & 2.69168212740063\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(stats)\n\nstats::t.test(msf_sc_group_1, msf_sc_group_2, alternative = \"less\")\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  msf_sc_group_1 and msf_sc_group_2\n#> t = -0.17, df = 118, p-value = 0.43\n#> alternative hypothesis: true difference in means is less than 0\n#> 95 percent confidence interval:\n#>    -Inf 759.34\n#> sample estimates:\n#> mean of x mean of y \n#>    103564    103651\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(dplyr)\n\ndplyr::tibble(\n  name = c(\"mean_group_1\", \"mean_group_2\", \"diff\"),\n  value = c(\n  stats_sum_group_1$mean, stats_sum_group_2$mean, \n  stats_sum_group_2$mean - stats_sum_group_1$mean\n  )\n)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r}\n\\hline\nname & value\\\\\n\\hline\nmean\\_group\\_1 & 103564.48\\\\\n\\hline\nmean\\_group\\_2 & 103651.49\\\\\n\\hline\ndiff & 87.01\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\nSee @frey2022 [pp. 224-227] to learn more.\n\n$$\nd = \\cfrac{\\mu_{1} - \\mu_{2}}{\\sigma_{e}}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(effsize)\n\neffsize::cohen.d(msf_sc_group_1, msf_sc_group_2)\n#> \n#> Cohen's d\n#> \n#> d estimate: -0.016915 (negligible)\n#> 95 percent confidence interval:\n#>    lower    upper \n#> -0.20387  0.17004\n```\n:::\n",
    "supporting": [
      "appendice-ch-6_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}