editor: source

execute:
  cache: false
  freeze: auto

profile:
  group:
    - [gfm, html, pdf, revealjs]
  default: pdf

book:
  title: "Is latitude associated with human circadian rhythms?"
  author: "Daniel Vartanian"
  keyword: >
    chronobiology. biological rhythms. chronotype. circadian phenotype. sleep.
    complex systems. entrainment. latitude. mctq.
  language: en-us
  license: "Creative Commons Attribution 4.0 International (CC BY 4.0)"
  publisher: "University of São Paulo"
  publisher-place: "São Paulo, SP, Brazil"
  submitted: 2024
  url: https://danielvartan.github.io/mastersthesis/
  site-url: https://danielvartan.github.io/mastersthesis/
  repo-url: https://github.com/danielvartan/mastersthesis/
  issue-url: https://github.com/danielvartan/mastersthesis/issues/
  repo-branch: main

citation:
  type: thesis
  url: https://danielvartan.github.io/mastersthesis/
google-scholar: false

bibliography: references.bib
