brand: false

project:
  type: book
  output-dir: _print
  pre-render: "R/_pre-render-pdf.R"
  post-render: "R/_post-render-pdf.R"

filters:
  - latex-environment
commands:
  - legend
  - brandorange
  - brandblack

execute:
  echo: false

book:
  author: "Daniel Kachvartanian de Azevedo"
  date: "2024-11-27"
  date-format: "YYYY"
  chapters:
    - index.qmd
    - qmd/chapter-2.qmd
    - qmd/chapter-3.qmd
    - qmd/chapter-4.qmd
    - qmd/chapter-5.qmd
    - qmd/chapter-6.qmd

format:
  abnt-pdf:
    zotero: true
    toc-depth: 2
    biblio-style: apa
    biblio-title: REFERENCES
    biblio-footnote: >
      In accordance with the American Psychological Association
      (APA) Style, 7th edition.
    bibhang: 0.5cm
    bibparsep: 1ex
    body-color: "142A32" # Brand Black
    colorlinks: true
    linkcolor: brand-orange
    filecolor: brand-orange
    citecolor: brand-orange
    urlcolor: brand-orange
    location: "São Paulo"
    supervisor: "Camilo Rodrigues Neto"
    academic-title: "Master"
    academic-degree: "Master of Science"
    type-of-work: "Thesis"
    area-of-concentration: "Complex Systems"
    university: "University of São Paulo"
    school: "School of Arts, Sciences and Humanities"
    program: "Graduate Program in Complex Systems Modeling"
    version-note: "Corrected version"
    include-in-header: tex/include-in-header.tex
    include-before-body: tex/include-before-body.tex
    include-after-body: tex/include-after-body.tex
