editor: source

execute:
  cache: false # "Danger Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!
                # Goddammit! What did I tell you?

profile:
  group:
    - [gfm, html, pdf, revealjs]
  default: pdf

book:
  title: "Is Latitude Associated with Chronotype?"
  keyword: >
    Complexity science. Complex systems. Chronobiology. Biological rhythms.
    Chronotypes. Circadian phenotypes. Sleep. Entrainment. Latitude. MCTQ.
  language: en
  license: "Creative Commons Attribution 4.0 International (CC BY 4.0)"
  submitted: 2025
  favicon: images/favicon.png
  url: https://danielvartan.github.io/mastersthesis/
  site-url: https://danielvartan.github.io/mastersthesis/
  repo-url: https://github.com/danielvartan/mastersthesis/
  issue-url: https://github.com/danielvartan/mastersthesis/issues/
  repo-branch: main

citation:
  type: thesis
  publisher: "University of São Paulo"
  publisher-place: "São Paulo, SP, Brazil"
  doi: "10.17605/OSF.IO/S4TBZ"
  url: https://danielvartan.github.io/mastersthesis/
  pdf-url: https://danielvartan.github.io/mastersthesis/print/index.pdf

google-scholar: true
bibliography: references.bib
