project:
  type: book
  output-dir: _web
  pre-render: "R/_pre-render-html.R"
  post-render: "R/_post-render-html.R"

book:
  author: "Daniel Vartanian"
  date: today
  date-format: "YYYY-MM-DD"
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: file-earmark-pdf-fill
        href: index.pdf
  chapters:
    - index.qmd
    - part: "Preliminary sections"
      chapters:
        - qmd/acknowledgments.qmd
        - qmd/epigraph.qmd
        - qmd/vernacular-abstract.qmd
        - qmd/foreign-abstract.qmd
    - part: "Chapters"
      chapters:
        - qmd/chapter-1.qmd
        - qmd/chapter-2.qmd
        - qmd/chapter-3.qmd
        - qmd/chapter-4.qmd
        - qmd/chapter-5.qmd
        - qmd/chapter-6.qmd
    - qmd/references.qmd
  appendices:
    - qmd/supplementary-material-1.qmd
    - qmd/supplementary-material-2.qmd
    - qmd/supplementary-material-3.qmd
    - qmd/supplementary-material-4.qmd
    - qmd/supplementary-material-5.qmd
    - qmd/supplementary-material-6.qmd
    - qmd/supplementary-material-7.qmd
    - qmd/supplementary-material-8.qmd
    - qmd/supplementary-material-10.qmd
  comments:
    hypothesis:
      theme: clean
      openSidebar: false

format:
  html:
    date-format: "YYYY-MM-DD"
    open-graph: true
    locale: en
    code-fold: true
    code-link: true
    code-tools: true
    cap-location: top
    df-print: paged
    fig-align: center
    number-depth: 5
    reader-mode: false
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/web.scss]
