project:
  type: book
  output-dir: _web
  pre-render: "R/_pre-render-html.R"
  post-render: "R/_post-render-html.R"

book:
  date: today
  date-format: "YYYY-MM-DD"
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: file-earmark-pdf-fill
        href: index.pdf
  chapters:
    - index.qmd
    - part: "Preliminary Pages"
      chapters:
        - qmd/errata.qmd
        - qmd/inscription.qmd
        - qmd/acknowledgments.qmd
        - qmd/epigraph.qmd
        - qmd/vernacular-abstract.qmd
        - qmd/foreign-abstract.qmd
        - qmd/list-of-abbreviations.qmd
        - qmd/list-of-symbols.qmd
    - part: "Chapters"
      chapters:
        - qmd/chapter-1.qmd
        - qmd/chapter-2.qmd
        - qmd/chapter-3.qmd
        - qmd/chapter-4.qmd
        - qmd/chapter-5.qmd
        - qmd/chapter-6.qmd
        - qmd/chapter-7.qmd
    - qmd/references.qmd
    - qmd/glossary.qmd
  appendices:
    - qmd/appendice-chapter-1.qmd
    - qmd/appendice-chapter-2.qmd
    - qmd/appendice-chapter-3.qmd
    - qmd/appendice-chapter-4.qmd
    - qmd/appendice-chapter-5.qmd
    - qmd/appendice-chapter-6.qmd

format:
  html:
    date-format: "YYYY-MM-DD"
    open-graph: true
    locale: en
    number-depth: 5
    code-link: true
    code-fold: show
    cap-location: top
    reader-mode: false
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/web.scss]
