project:
  type: book
  output-dir: _web
  pre-render: "R/_pre-render-html.R"
  post-render: "R/_post-render-html.R"

book:
  author: "Daniel Vartanian"
  date: today
  date-format: "YYYY-MM-DD"
  reader-mode: true
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: file-earmark-pdf-fill
        href: ../print/index.pdf
  chapters:
    - index.qmd
    - part: "Preliminary Sections"
      chapters:
        - qmd/acknowledgments.qmd
        - qmd/epigraph.qmd
        - qmd/vernacular-abstract.qmd
        - qmd/foreign-abstract.qmd
    - part: "Chapters"
      chapters:
        - qmd/chapter-1.qmd
        - qmd/chapter-2.qmd
        - qmd/chapter-3.qmd
        - qmd/chapter-4.qmd
        - qmd/chapter-5.qmd
        - qmd/chapter-6.qmd
    - qmd/references.qmd
  appendices:
    - qmd/supplementary-material-1.qmd
    - qmd/supplementary-material-2.qmd
    - qmd/supplementary-material-3.qmd
    - qmd/supplementary-material-4.qmd
    - qmd/supplementary-material-5.qmd
    - qmd/supplementary-material-6.qmd
    - qmd/supplementary-material-7.qmd
    - qmd/supplementary-material-8.qmd
    - qmd/supplementary-material-9.qmd
    - qmd/supplementary-material-10.qmd
  comments:
    hypothesis:
      theme: clean
      openSidebar: false

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    dev: "ragg_png" # Set `AGG` as the backend of your graphic device.
    dev.args:
      bg: "transparent"

format:
  html:
    date-format: "YYYY-MM-DD"
    open-graph: true
    locale: en
    language: en
    code-fold: true
    code-link: true
    code-tools: false
    df-print: paged
    cap-location: top
    fig-align: center
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    repo-actions: true
    link-external-icon: false
    link-external-newwindow: false
    theme: [cosmo, brand, scss/web.scss]
