{
  "hash": "206dd7e2cffe9aa633d2f53cfec0de9f",
  "result": {
    "markdown": "# Appendice: Chapter 4 supplemental material\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note}\nYou are reading the work-in-progress of this thesis. This chapter should be readable but is currently undergoing final polishing.\n:::\n\n\n\n## Data wrangling\n\nThe data wrangling processes were performed using the  [`targets`](https://github.com/ropensci/targets) R package. A graphical pipeline of the process can be visualized below.\n\nThe analyses are 100% reproducible. You can find all the code used in this thesis along with the computational notebooks at <https://github.com/danielvartan/mastersthesis/>.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(dplyr)\n# library(here)\nlibrary(targets)\n# library(tidyr)\n\ndata <- \n  targets::tar_read(\"geocoded_data\", store = here::here(\"_targets\")) |>\n  dplyr::select(\n    age, sex, state, region, latitude, longitude, height, weight, work, study,\n    msf_sc, sjl, le_week, \n    ) |>\n  tidyr::drop_na(msf_sc, age, sex, latitude)\n```\n:::\n\n\n\n## Distribution of main variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(hms)\n# library(magrittr)\n\nsource(here::here(\"R/test_normality.R\"))\nsource(here::here(\"R/utils.R\"))\n\ncol <- \"age\"\n\nstats <- data |> \n  magrittr::extract2(col) |> \n  test_normality(\n    name = col, \n    threshold = hms::parse_hms(\"12:00:00\"), \n    remove_outliers = FALSE, \n    iqr_mult = 1.5, \n    log_transform = FALSE,\n    density_line = TRUE, \n    text_size = text_size,\n    print = TRUE\n  )\n#> # A tibble: 14 x 2\n#>   name    value           \n#>   <chr>   <chr>           \n#> 1 n       79198           \n#> 2 n_rm_na 79198           \n#> 3 n_na    0               \n#> 4 mean    31.9838074965417\n#> 5 var     85.2414919292643\n#> 6 sd      9.23263190695179\n#> # i 8 more rows\n\nstats$stats |> list_as_tibble()\n```\n\n::: {#fig-ap-ch-4-age-var-distribution-1 .cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 79198\\\\\n\\hline\nn\\_rm\\_na & 79198\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 31.9838074965417\\\\\n\\hline\nvar & 85.2414919292643\\\\\n\\hline\nsd & 9.23263190695179\\\\\n\\hline\nmin & 18\\\\\n\\hline\nq\\_1 & 24.7222222222222\\\\\n\\hline\nmedian & 30.5388888888889\\\\\n\\hline\nq\\_3 & 37.61875\\\\\n\\hline\nmax & 58.7861111111111\\\\\n\\hline\niqr & 12.8965277777778\\\\\n\\hline\nskewness & 0.665751526654394\\\\\n\\hline\nkurtosis & 2.82381488030798\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-age-var-distribution-1.png){#fig-ap-ch-4-age-var-distribution-2}\n:::\n:::\n\n\n\n## Geographic distribution\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(rutils)\n\nsource(here::here(\"R/plot_brazil_uf_map.R\"))\n\nrutils:::assert_internet()\n\nbrazil_uf_map <- \n  data |> \n  plot_brazil_uf_map(option = \"viridis\", text_size = 10)\n```\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-brazil-uf-map-1.png){#fig-ap-ch-4-brazil-uf-map}\n:::\n:::\n\n\n\n## Age pyramid\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n\nsource(here::here(\"R/plot_age_pyramid.R\"))\n\nage_pyramid <- \n  data |> \n  plot_age_pyramid(\n    interval = 10, \n    na_rm = TRUE, \n    text_size = text_size\n  )\n```\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-age-pyramid-1.png){#fig-ap-ch-4-age-pyramid}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## Correlation matrix\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n\nsource(here::here(\"R/plot_ggcorrplot.R\"))\n\ncols <- c(\"sex\", \"age\", \"latitude\", \"longitude\", \"msf_sc\", \"sjl\", \"le_week\")\n\nggcorrplot <-\n  data |>\n  plot_ggcorrplot(\n    cols = cols, \n    na_rm = TRUE, \n    text_size = text_size, \n    hc_order = TRUE\n    )\n```\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-correlation-matrix-1.png){#fig-ap-ch-4-correlation-matrix}\n:::\n:::\n\n\n\n## Age series\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(latex2exp)\n\nsource(here::here(\"R/plot_age_series.R\"))\n\ncol <- \"msf_sc\"\ny_lab <- latex2exp::TeX(\"Local time ($MSF_{sc}$)\")\n\ndata |>\n  dplyr::filter(age <= 50) |>\n  plot_age_series(\n    col = col, \n    y_lab = y_lab, \n    line_width = 2, \n    boundary = 0.5, \n    point_size = 1,\n    error_bar_width = 0.5, \n    error_bar_linewidth = 0.5, \n    error_bar = TRUE,\n    text_size = text_size\n    )\n```\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-age-series-1.png){#fig-ap-ch-4-age-series}\n:::\n:::\n\n\n\n## Chronotype\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(latex2exp)\n\nsource(here::here(\"R/plot_chronotype.R\"))\n\ncol <- \"msf_sc\"\ny_lab <- latex2exp::TeX(\"Local time ($MSF_{sc}$)\")\n\ndata |>\n  plot_chronotype(\n    col = col, \n    x_lab = \"Frequency (%)\",\n    y_lab = y_lab,\n    col_width = 0.8, \n    col_border = 0.6, \n    text_size = text_size,\n    legend_position = \"right\",\n    chronotype_cuts = FALSE\n  )\n```\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-chronotype-1.png){#fig-ap-ch-4-chronotype}\n:::\n:::\n\n\n\n## Latitude series\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(latex2exp)\n\nsource(here::here(\"R/plot_latitude_series.R\"))\n\ncol <- \"msf_sc\"\ny_lab <- latex2exp::TeX(\"$MSF_{sc} \\\\pm SEM$\")\n\ndata |>\n  dplyr::filter(age <= 50) |>\n  plot_latitude_series(\n    col = col, \n    y_lab = y_lab, \n    line_width = 2, \n    point_size = 3,\n    error_bar_width = 0.5, \n    error_bar_linewidth = 1, \n    error_bar = TRUE,\n    text_size = text_size\n  )\n```\n\n::: {.cell-output-display}\n![](appendice-ch-4_files/figure-pdf/fig-ap-ch-4-latitude-series-1.png){#fig-ap-ch-4-latitude-series}\n:::\n:::\n\n\n\n## Statistics\n\n### Numerical variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\ncol <- \"age\"\n\ndata |>\n  magrittr::extract2(col) |>\n  stats_sum(print = FALSE) |>\n  list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 79198\\\\\n\\hline\nn\\_rm\\_na & 79198\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 31.9838074965417\\\\\n\\hline\nvar & 85.2414919292643\\\\\n\\hline\nsd & 9.23263190695179\\\\\n\\hline\nmin & 18\\\\\n\\hline\nq\\_1 & 24.7222222222222\\\\\n\\hline\nmedian & 30.5388888888889\\\\\n\\hline\nq\\_3 & 37.61875\\\\\n\\hline\nmax & 58.7861111111111\\\\\n\\hline\niqr & 12.8965277777778\\\\\n\\hline\nskewness & 0.665751526654394\\\\\n\\hline\nkurtosis & 2.82381488030798\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\n### Sex\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# See <https://sidra.ibge.gov.br> to learn more.\n\n# library(dplyr)\nlibrary(magrittr)\n# library(sidrar)\n# library(stringr)\n# library(rutils)\n\nrutils:::assert_internet()\n\n# Brazil's 2010 census data\ncensus_data <- \n  sidrar::get_sidra(x = 1378) %>% # Don't change the pipe\n  dplyr::filter(\n    Sexo %in% c(\"Homens\", \"Mulheres\", \"Total\"),\n    stringr::str_detect(Idade, \"^(1[8-9]|[2-9][0-9]+) (ano|anos)$\"),\n    .[[13]] == \"Total\", \n    .[[19]] == \"Total\"\n    ) |>\n  dplyr::transmute(\n    sex = dplyr::case_when(\n      Sexo == \"Homens\" ~ \"Male\",\n      Sexo == \"Mulheres\" ~ \"Female\",\n      Sexo == \"Total\" ~ \"Total\"\n    ),\n    value = Valor\n  ) |>\n  dplyr::group_by(sex) |>\n  dplyr::summarise(n = sum(value)) |>\n  dplyr::ungroup()\n\ncensus_data <- \n  dplyr::bind_rows(\n    census_data |>\n      dplyr::filter(sex != \"Total\") |>\n      dplyr::mutate(\n        n_rel = n / sum(n[sex != \"Total\"]),\n        n_per = round(n_rel * 100, 3)\n      ),\n    census_data |>\n      dplyr::filter(sex == \"Total\") |>\n      dplyr::mutate(n_rel = 1, n_per = 100)\n  ) |>\n  dplyr::as_tibble() |>\n  dplyr::arrange(sex)\n\ncount <- data |>\n  dplyr::select(sex) |>\n  dplyr::group_by(sex) |>\n  dplyr::summarise(n = dplyr::n()) |>\n  dplyr::ungroup() |>\n  dplyr::mutate(\n    n_rel = n / sum(n),\n    n_per = round(n_rel * 100, 3)\n  ) |>\n  dplyr::arrange(dplyr::desc(n_rel)) |>\n  dplyr::bind_rows(\n    dplyr::tibble(\n      sex = \"Total\",\n      n = nrow(tidyr::drop_na(data, sex)),\n      n_rel = 1, \n      n_per = 100\n    )\n  )\n\ncount <- \n  dplyr::left_join(\n    count, census_data, \n    by = \"sex\", \n    suffix = c(\"_sample\", \"_census\")\n  ) |>\n  dplyr::mutate(\n    n_rel_diff = n_rel_sample - n_rel_census,\n    n_per_diff = n_per_sample - n_per_census\n  ) |>\n  dplyr::relocate(\n    sex, n_sample, n_census, n_rel_sample, n_rel_census, n_rel_diff,\n    n_per_sample, n_per_census, n_per_diff\n  )\n\n## Difference from the sample to the census\ncount\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r|r|r|r|r|r}\n\\hline\nsex & n\\_sample & n\\_census & n\\_rel\\_sample & n\\_rel\\_census & n\\_rel\\_diff & n\\_per\\_sample & n\\_per\\_census & n\\_per\\_diff\\\\\n\\hline\nFemale & 52463 & 69631672 & 0.662 & 0.518 & 0.144 & 66.243 & 51.793 & 14.45\\\\\n\\hline\nMale & 26735 & 64809723 & 0.338 & 0.482 & -0.144 & 33.757 & 48.207 & -14.45\\\\\n\\hline\nTotal & 79198 & 134441395 & 1.000 & 1.000 & 0.000 & 100.000 & 100.000 & 0.00\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncount |> dplyr::select(sex, n_per_sample, n_per_census, n_per_diff)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r}\n\\hline\nsex & n\\_per\\_sample & n\\_per\\_census & n\\_per\\_diff\\\\\n\\hline\nFemale & 66.243 & 51.793 & 14.45\\\\\n\\hline\nMale & 33.757 & 48.207 & -14.45\\\\\n\\hline\nTotal & 100.000 & 100.000 & 0.00\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nsum(count$n_per_diff)\n#> [1] -7.105427e-15\n```\n:::\n\n\n\n### Sex and Age\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(dplyr)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\nvalue <- \"Male\"\n\ndata |>\n  dplyr::filter(sex == value) |>\n  magrittr::extract2(\"age\") |>\n  stats_sum(print = FALSE) |>\n  list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 26735\\\\\n\\hline\nn\\_rm\\_na & 26735\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & 32.4343759740665\\\\\n\\hline\nvar & 80.9906211885464\\\\\n\\hline\nsd & 8.99947893983571\\\\\n\\hline\nmin & 18\\\\\n\\hline\nq\\_1 & 25.5388888888889\\\\\n\\hline\nmedian & 31.2583333333333\\\\\n\\hline\nq\\_3 & 37.9319444444444\\\\\n\\hline\nmax & 58.7722222222222\\\\\n\\hline\niqr & 12.3930555555556\\\\\n\\hline\nskewness & 0.617696405622681\\\\\n\\hline\nkurtosis & 2.84390555184727\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# See <https://sidra.ibge.gov.br> to learn more.\n\n# library(dplyr)\nlibrary(magrittr)\n# library(sidrar)\n# library(stats)\n# library(stringr)\n# library(rutils)\n\nrutils:::assert_internet()\n\n# Brazil's 2010 census data\ncensus_data <- \n  sidrar::get_sidra(x = 1378) %>% # Don't change the pipe\n  dplyr::filter(\n    Sexo %in% c(\"Homens\", \"Mulheres\", \"Total\"),\n    stringr::str_detect(Idade, \"^(1[8-9]|[2-9][0-9]+) (ano|anos)$\"),\n    .[[13]] == \"Total\", \n    .[[19]] == \"Total\"\n    ) |>\n  dplyr::transmute(\n    sex = dplyr::case_when(\n      Sexo == \"Homens\" ~ \"Male\",\n      Sexo == \"Mulheres\" ~ \"Female\",\n      Sexo == \"Total\" ~ \"Total\"\n    ),\n    age = as.numeric(stringr::str_extract(Idade, \"\\\\d+\")),\n    value = Valor\n  ) |>\n  dplyr::group_by(sex) |>\n  dplyr::summarise(\n    mean = stats::weighted.mean(age, value),\n    sd = sqrt(Hmisc::wtd.var(age, value))\n  ) |> \n  dplyr::ungroup() |>\n  dplyr::mutate(\n    min = c(18, 18, 18),\n    max = c(100, 100, 100)\n  ) |>\n  dplyr::relocate(sex, mean, sd, min, max) |>\n  dplyr::as_tibble()\n\ncount <- data |>\n  dplyr::select(sex, age) |>\n  dplyr::group_by(sex) |>\n  dplyr::mutate(sex = as.character(sex)) |>\n  dplyr::summarise(\n    mean = mean(age, na.rm = TRUE), \n    sd = stats::sd(age, na.rm = TRUE),\n    min = min(age, na.rm = TRUE), \n    max = max(age, na.rm = TRUE)\n    ) |>\n  dplyr::ungroup() |>\n  dplyr::bind_rows(\n    dplyr::tibble(\n      sex = \"Total\",\n      mean = mean(data$age, na.rm = TRUE), \n      sd = stats::sd(data$age, na.rm = TRUE),\n      min = min(data$age, na.rm = TRUE), \n      max = max(data$age, na.rm = TRUE)\n    )\n  )\n  \ncount <- \n  dplyr::left_join(\n    count, \n    census_data, \n    by = \"sex\", \n    suffix = c(\"_sample\", \"_census\")\n  ) |>\n  dplyr::mutate(mean_diff = mean_sample - mean_census) |>\n  dplyr::relocate(\n    sex, mean_sample, mean_census, mean_diff, sd_sample, sd_census, \n    min_sample, min_census, max_sample, max_census\n  )\n\ncount\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r|r|r|r|r|r|r}\n\\hline\nsex & mean\\_sample & mean\\_census & mean\\_diff & sd\\_sample & sd\\_census & min\\_sample & min\\_census & max\\_sample & max\\_census\\\\\n\\hline\nFemale & 31.754 & 41.645 & -9.890 & 9.341 & 16.907 & 18 & 18 & 58.786 & 100\\\\\n\\hline\nMale & 32.434 & 40.373 & -7.938 & 8.999 & 16.200 & 18 & 18 & 58.772 & 100\\\\\n\\hline\nTotal & 31.984 & 41.032 & -9.048 & 9.233 & 16.582 & 18 & 18 & 58.786 & 100\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n\ncount |> \n  dplyr::select(\n    sex, mean_sample, mean_census, mean_diff, sd_sample, sd_census\n    )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r|r|r}\n\\hline\nsex & mean\\_sample & mean\\_census & mean\\_diff & sd\\_sample & sd\\_census\\\\\n\\hline\nFemale & 31.754 & 41.645 & -9.890 & 9.341 & 16.907\\\\\n\\hline\nMale & 32.434 & 40.373 & -7.938 & 8.999 & 16.200\\\\\n\\hline\nTotal & 31.984 & 41.032 & -9.048 & 9.233 & 16.582\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n\nsum(count$mean_diff)\n#> [1] -26.87654\n```\n:::\n\n\n\n### Longitudinal range\n\n#### Sample\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(dplyr)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\nstats <- \n  data |>\n  magrittr::extract2(\"longitude\") |>\n  stats_sum(print = FALSE)\n\nabs(stats$max - stats$min)\n#> [1] 33.023\nstats |> list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 79198\\\\\n\\hline\nn\\_rm\\_na & 79198\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & -45.9455401815147\\\\\n\\hline\nvar & 18.9406905927715\\\\\n\\hline\nsd & 4.35209037047388\\\\\n\\hline\nmin & -67.9869962\\\\\n\\hline\nq\\_1 & -48.4296364\\\\\n\\hline\nmedian & -46.9249578\\\\\n\\hline\nq\\_3 & -43.7756411\\\\\n\\hline\nmax & -34.9639996\\\\\n\\hline\niqr & 4.6539953\\\\\n\\hline\nskewness & 0.0156480710174436\\\\\n\\hline\nkurtosis & 5.78918700160139\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\n#### Brazil\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(measurements)\n\nchange_sign <- function(x) x * (-1)\n\n## Ponta do Seixas, PB (7° 09′ 18″ S, 34° 47′ 34″ O)\nmin <- \n  measurements::conv_unit(\"34 47 34\", from = \"deg_min_sec\", to = \"dec_deg\") |>\n  as.numeric() |>\n  change_sign()\n\n## Nascente do rio Moa, AC (7° 32′ 09″ S, 73° 59′ 26″ O)\nmax <- \n  measurements::conv_unit(\"73 59 26\", from = \"deg_min_sec\", to = \"dec_deg\") |>\n  as.numeric() |>\n  change_sign()\n\nmin\n#> [1] -34.79278\nmax\n#> [1] -73.99056\nabs(max - min)\n#> [1] 39.19778\n```\n:::\n\n\n\n### Latitudinal range\n\n#### Sample\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(dplyr)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\nsource(here::here(\"R/utils.R\"))\n\nstats <- \n  data |>\n  magrittr::extract2(\"latitude\") |>\n  stats_sum(print = FALSE)\n\nabs(stats$max - stats$min)\n#> [1] 32.91596\nstats |> list_as_tibble()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|l}\n\\hline\nname & value\\\\\n\\hline\nn & 79198\\\\\n\\hline\nn\\_rm\\_na & 79198\\\\\n\\hline\nn\\_na & 0\\\\\n\\hline\nmean & -20.8338507528991\\\\\n\\hline\nvar & 40.2956396934244\\\\\n\\hline\nsd & 6.34788466289554\\\\\n\\hline\nmin & -30.1087672\\\\\n\\hline\nq\\_1 & -23.6820636\\\\\n\\hline\nmedian & -23.6820636\\\\\n\\hline\nq\\_3 & -19.9026404\\\\\n\\hline\nmax & 2.8071961\\\\\n\\hline\niqr & 3.7794232\\\\\n\\hline\nskewness & 1.40629570823769\\\\\n\\hline\nkurtosis & 4.67433697579443\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\n#### Brazil\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(measurements)\n\nchange_sign <- function(x) x * (-1)\n\n## Arroio Chuí, RS (33° 45′ 07″ S, 53° 23′ 50″ O)\nmin <- \n  measurements::conv_unit(\"33 45 07\", from = \"deg_min_sec\", to = \"dec_deg\") |>\n  as.numeric() |>\n  change_sign()\n\n## Nascente do rio Ailã, RR (5° 16′ 19″ N, 60° 12′ 45″ O)\nmax <- \n  measurements::conv_unit(\"5 16 19\", from = \"deg_min_sec\", to = \"dec_deg\") |>\n  as.numeric()\n\nmin\n#> [1] -33.75194\nmax\n#> [1] 5.271944\nabs(max - min)\n#> [1] 39.02389\n```\n:::\n\n\n\n### Region\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# See <https://sidra.ibge.gov.br> to learn more.\n\n# library(dplyr)\n# library(sidrar)\n# library(stats)\n# library(stringr)\n# library(rutils)\n\nrutils:::assert_internet()\n\n# Brazil's 2022 census data\ncensus_data <- \n  sidrar::get_sidra(x = 4714, variable = 93, geo = \"Region\") |>\n  dplyr::select(dplyr::all_of(c(\"Valor\", \"Grande Região\"))) |>\n  dplyr::transmute(\n    col = `Grande Região`,\n    n = Valor,\n    n_rel = n / sum(n),\n    n_per = round(n_rel * 100, 3)\n    ) |>\n  dplyr::mutate(\n    col = dplyr::case_when(\n      col == \"Norte\" ~ \"North\",\n      col == \"Nordeste\" ~ \"Northeast\",\n      col == \"Centro-Oeste\" ~ \"Midwest\",\n      col == \"Sudeste\" ~ \"Southeast\",\n      col == \"Sul\" ~ \"South\"\n    )\n  ) |>\n  dplyr::as_tibble() |>\n  dplyr::arrange(dplyr::desc(n_rel))\n\ncount <- data |> \n  magrittr::extract2(\"region\") |>\n  stats_sum(print = FALSE) |>\n  magrittr::extract2(\"count\") |>\n  dplyr::mutate(\n    n_rel = n / sum(n),\n    n_per = round(n_rel * 100, 3)\n    ) |>\n  dplyr::arrange(dplyr::desc(n_rel))\n\ncount <- \n  dplyr::left_join(\n    count, census_data, by = \"col\", suffix = c(\"_sample\", \"_census\")\n  ) |>\n  dplyr::mutate(\n    n_rel_diff = n_rel_sample - n_rel_census,\n    n_per_diff = n_per_sample - n_per_census\n  ) |>\n  dplyr::relocate(\n    col, n_sample, n_census, n_rel_sample, n_rel_census, n_rel_diff,\n    n_per_sample, n_per_census, n_per_diff\n  )\n\n## Difference from the sample to the census\ncount\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r|r|r|r|r|r}\n\\hline\ncol & n\\_sample & n\\_census & n\\_rel\\_sample & n\\_rel\\_census & n\\_rel\\_diff & n\\_per\\_sample & n\\_per\\_census & n\\_per\\_diff\\\\\n\\hline\nSoutheast & 47966 & 84847187 & 0.606 & 0.418 & 0.188 & 60.565 & 41.784 & 18.781\\\\\n\\hline\nSouth & 13560 & 29933315 & 0.171 & 0.147 & 0.024 & 17.122 & 14.741 & 2.381\\\\\n\\hline\nNortheast & 9138 & 54644582 & 0.115 & 0.269 & -0.154 & 11.538 & 26.910 & -15.372\\\\\n\\hline\nMidwest & 6563 & 16287809 & 0.083 & 0.080 & 0.003 & 8.287 & 8.021 & 0.266\\\\\n\\hline\nNorth & 1971 & 17349619 & 0.025 & 0.085 & -0.061 & 2.489 & 8.544 & -6.055\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncount |> dplyr::select(col, n_per_sample, n_per_census, n_per_diff)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r}\n\\hline\ncol & n\\_per\\_sample & n\\_per\\_census & n\\_per\\_diff\\\\\n\\hline\nSoutheast & 60.565 & 41.784 & 18.781\\\\\n\\hline\nSouth & 17.122 & 14.741 & 2.381\\\\\n\\hline\nNortheast & 11.538 & 26.910 & -15.372\\\\\n\\hline\nMidwest & 8.287 & 8.021 & 0.266\\\\\n\\hline\nNorth & 2.489 & 8.544 & -6.055\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nsum(count$n_per_diff)\n#> [1] 0.001\n```\n:::\n\n\n\n### State\n\n::: {.callout-note}\n## TODO\n\nCompare with 2022 census.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# library(here)\n# library(dplyr)\n# library(magrittr)\n\nsource(here::here(\"R/stats_sum.R\"))\n\ndata |> \n  magrittr::extract2(\"state\") |>\n  stats_sum(print = FALSE) |>\n  magrittr::extract2(\"count\") |>\n  dplyr::mutate(\n    n_rel = n / sum(n),\n    n_per = round(n_rel * 100, 3)\n    ) |>\n  dplyr::arrange(dplyr::desc(n_rel))\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}{l|r|r|r}\n\\hline\ncol & n & n\\_rel & n\\_per\\\\\n\\hline\nSão Paulo & 26379 & 0.333 & 33.308\\\\\n\\hline\nMinas Gerais & 10115 & 0.128 & 12.772\\\\\n\\hline\nRio de Janeiro & 9381 & 0.118 & 11.845\\\\\n\\hline\nParaná & 5517 & 0.070 & 6.966\\\\\n\\hline\nRio Grande do Sul & 4097 & 0.052 & 5.173\\\\\n\\hline\nSanta Catarina & 3946 & 0.050 & 4.982\\\\\n\\hline\nGoiás & 2674 & 0.034 & 3.376\\\\\n\\hline\nBahia & 2522 & 0.032 & 3.184\\\\\n\\hline\nEspírito Santo & 2091 & 0.026 & 2.640\\\\\n\\hline\nDistrito Federal & 2087 & 0.026 & 2.635\\\\\n\\hline\nPernambuco & 1550 & 0.020 & 1.957\\\\\n\\hline\nCeará & 1398 & 0.018 & 1.765\\\\\n\\hline\nMato Grosso do Sul & 1014 & 0.013 & 1.280\\\\\n\\hline\nPará & 938 & 0.012 & 1.184\\\\\n\\hline\nRio Grande do Norte & 789 & 0.010 & 0.996\\\\\n\\hline\nMato Grosso & 788 & 0.010 & 0.995\\\\\n\\hline\nParaíba & 773 & 0.010 & 0.976\\\\\n\\hline\nMaranhão & 652 & 0.008 & 0.823\\\\\n\\hline\nSergipe & 533 & 0.007 & 0.673\\\\\n\\hline\nAlagoas & 526 & 0.007 & 0.664\\\\\n\\hline\nRondônia & 401 & 0.005 & 0.506\\\\\n\\hline\nPiauí & 395 & 0.005 & 0.499\\\\\n\\hline\nTocantins & 268 & 0.003 & 0.338\\\\\n\\hline\nAcre & 132 & 0.002 & 0.167\\\\\n\\hline\nRoraima & 119 & 0.002 & 0.150\\\\\n\\hline\nAmapá & 113 & 0.001 & 0.143\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n:::\n:::\n",
    "supporting": [
      "appendice-ch-4_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}