# library(checkmate)
# library(cli)
# library(dplyr)
library(magrittr)
# library(tidyr)

source(here::here("R", "get_inpe_data.R"))
source(here::here("R", "get_time_and_date_data.R"))

add_solar_data <- function(
    data,
    inpe_data = get_inpe_data(),
    time_and_date_data = get_time_and_date_data()
  ) {
  assertion_vars <- c("timestamp", "latitude", "longitude")

  checkmate::assert_tibble(data)
  checkmate::assert_subset(assertion_vars, names(data))
  checkmate::assert_tibble(inpe_data)
  checkmate::assert_tibble(time_and_date_data)

  cli::cli_progress_step("Adding solar data")

  data |>
    add_ghi(inpe_data) |>
    add_equinox_and_solstice(time_and_date_data) |>
    add_sun_time()
}

# library(checkmate)
# library(dplyr)

source(here::here("R", "get_inpe_data.R"))

add_ghi <- function(data, inpe_data = get_inpe_data()) {
  checkmate::assert_tibble(data)
  checkmate::assert_tibble(inpe_data)

  out <- data |>
    dplyr::left_join(
      inpe_data,
      by = dplyr::join_by(
        closest(latitude >= latitude),
        closest(longitude >= longitude)
      ),
      suffix = c("", "_inpe")
    ) |>
    dplyr::mutate(
      month =
        timestamp |>
        lubridate::month(abbr = FALSE, label = TRUE) |>
        tolower(),
      ghi_month = dplyr::case_when(
        month == "january" ~ january,
        month == "february" ~ february,
        month == "march" ~ march,
        month == "april" ~ april,
        month == "may" ~ may,
        month == "june" ~ june,
        month == "july" ~ july,
        month == "august" ~ august,
        month == "september" ~ september,
        month == "october" ~ october,
        month == "november" ~ november,
        month == "december" ~ december
      )
    ) |>
    dplyr::rename(ghi_annual = annual) |>
    dplyr::select(-dplyr::ends_with("_inpe")) |>
    dplyr::select(
      -dplyr::all_of(
        c(
          "month", "january", "february", "march", "april", "may", "june",
          "july", "august", "september", "october", "november", "december"
        )
      )
    ) |>
    dplyr::relocate(ghi_month, ghi_annual, .after = longitude)

  if (out |> dplyr::pull(ghi_month) |> is.na() |> all()) {
    cli::cli_alert_danger(
      paste0(
        "An error occurred due to an invalid locale value. ",
        "Ensure that your system locale is set to English. ",
        "({.strong Sys.setlocale(locale = 'en_US.utf8')}). This step is ",
        "crucial for the proper functioning of the data wrangling functions. ",
        "{.strong Without it, the data generated by the pipeline will be ",
        "{cli::col_red('invalid')}}! ",
        "Run {.strong {cli::col_blue('?Sys.setlocale')}} to investigate ",
        "the issue, or reach out to the thesis author for assistance."
      ),
      wrap = TRUE
    )

    cat("\n")

    cli::cli_alert_info(
      paste0(
        "Errors related to locale values are likely caused by differences in ",
        "how operating systems handle locale settings."
      ),
      wrap = TRUE
    )
  } else {
    out
  }
}

# library(checkmate)
# library(dplyr)
library(magrittr)
# library(tidyr)

source(here::here("R", "get_time_and_date_data.R"))

add_equinox_and_solstice <- function(
    data,
    time_and_date_data = get_time_and_date_data()
  ) {
  checkmate::assert_tibble(data)
  checkmate::assert_tibble(time_and_date_data)

  data |>
    dplyr::left_join(
      time_and_date_data |>
        dplyr::filter(
          year %in% (
            data |>
              dplyr::pull(timestamp) |>
              lubridate::year() |>
              unique() %>%
              c((.[1]) - 1, .)
          )
        ) |>
        dplyr::select(-year) |>
        dplyr::mutate(
          dplyr::across(
            .cols = dplyr::everything(),
            .fns = ~ lubridate::with_tz(.x, tz = "America/Sao_Paulo")
          )
        ) |>
        tidyr::expand(
          march_equinox, june_solstice, september_equinox,
          december_solstice
        ),
      by = dplyr::join_by(
        closest(timestamp >= march_equinox),
        closest(timestamp >= june_solstice),
        closest(timestamp >= september_equinox),
        closest(timestamp >= december_solstice)
      )
    ) |>
    dplyr::relocate(
      march_equinox, june_solstice, september_equinox, december_solstice,
      .after = ghi_annual
    )
}

# library(checkmate)
# library(dplyr)
# library(suntools)

add_sun_time <- function(data) {
  checkmate::assert_tibble(data)

  data |>
    dplyr::mutate(
      dplyr::across(
        .cols = dplyr::all_of(
          c(
            "march_equinox", "june_solstice", "september_equinox",
            "december_solstice"
          )
        ),
        .fns = ~ suntools::sunriset(
          matrix(
            c(
              longitude |> tidyr::replace_na(51.48208), # Placeholder
              latitude |> tidyr::replace_na(-0.0045417) # Placeholder
            ),
            nrow = dplyr::n()
          ),
          dateTime = .x,
          direction = "sunrise", # "sunset"
          POSIXct.out = TRUE
        ) |>
          dplyr::pull(time),
        .names = "{.col}_sunrise"
      ),
      dplyr::across(
        .cols = dplyr::all_of(
          c(
            "march_equinox", "june_solstice", "september_equinox",
            "december_solstice"
          )
        ),
        .fns = ~ suntools::sunriset(
          matrix(
            c(
              longitude |> tidyr::replace_na(51.48208), # Placeholder
              latitude |> tidyr::replace_na(-0.0045417) # Placeholder
            ),
            nrow = dplyr::n()
          ),
          dateTime = .x,
          direction = "sunset",
          POSIXct.out = TRUE
        ) |>
          dplyr::pull(time),
        .names = "{.col}_sunset"
      ),
      dplyr::across(
        .cols = dplyr::matches("_sunrise$|_sunset$"),
        .fns = ~ dplyr::if_else(
          is.na(latitude) | is.na(longitude),
          NA,
          .x
        )
      )
    ) |>
    dplyr::mutate(
      dplyr::across(
        .cols = dplyr::all_of(
          c(
            "march_equinox", "june_solstice", "september_equinox",
            "december_solstice"
          )
        ),
        .fns = ~
          (get(paste0(dplyr::cur_column(), "_sunset")) -
             get(paste0(dplyr::cur_column(), "_sunrise"))) |>
          lubridate::as.duration(),
        .names = "{.col}_daylight"
      )
    ) |>
    dplyr::relocate(dplyr::matches("^march_"), .before = june_solstice) |>
    dplyr::relocate(dplyr::matches("^june_"), .before = september_equinox) |>
    dplyr::relocate(
      dplyr::matches("^september_"), .before = december_solstice
    ) |>
    dplyr::relocate(dplyr::matches("^december_"), .before = height)
}
